window.SONGS = [
  {
    id: "4g7ASoGYRujjvNL6DHX9j8",
    title: "24.000 Baci",
    artist: "Adriano Celentano",
    year: "1963",
  },
  {
    id: "3yGyWqmw9eCQPdJJ6iJLWs",
    title: "4/3/1943",
    artist: "Lucio Dalla",
    year: "1970",
  },
  {
    id: "3q3hFN65AWi7IjVwxN6juk",
    title: "46",
    artist: "Cesare Cremonini",
    year: "2015",
  },
  {
    id: "0x4HvQuUbXAa4bYForAK7S",
    title: "A mano a mano",
    artist: "Rino Gaetano",
    year: "1981",
  },
  {
    id: "7rl7TNsfJiJJ3BY47peVSm",
    title: "A un passo da te",
    artist: "MINACELENTANO",
    year: "2016",
  },
  {
    id: "7EM7aTxoicXDjIy3gK6Pnu",
    title: "A Volte Esagero",
    artist: "Marracash;Salmo;Coez",
    year: "2015",
  },
  {
    id: "6DaqDhzDgtIPLeowS4N3kA",
    title: "Abbracciami",
    artist: "Marino marini",
    year: "1958",
  },
  {
    id: "1N46SW28bpacvXmNYP6PTB",
    title: "Acqua azzurra, acqua chiara",
    artist: "Lucio Battisti",
    year: "1970",
  },
  {
    id: "1e4ZMHWU3wxRzeDtfITbhT",
    title: "Acqua e sale",
    artist: "MINACELENTANO",
    year: "1998",
  },
  {
    id: "5IfoBzoixewbULHm5mHLJZ",
    title: "Acqua e Sapone",
    artist: "Stadio",
    year: "1983",
  },
  {
    id: "0uhbLe0AwiGMBcFGk3fI6x",
    title: "Ad esempio a me piace il sud",
    artist: "Rino Gaetano",
    year: "1973",
  },
  {
    id: "6sKdsm15cungJazNyWHdOE",
    title: "Adelante! Adelante!",
    artist: "Francesco De Gregori",
    year: "1992",
  },
  {
    id: "0INaMqjJJe1BZpnWuCxDzt",
    title: "Ai Se Eu Te Pego",
    artist: "Michel Teló",
    year: "2011",
  },
  {
    id: "7N1SQcqAkSvUgnlvrU0Et8",
    title: "Aida",
    artist: "Rino Gaetano",
    year: "1977",
  },
  {
    id: "53MYtv4tzLYg1hbu13Qbc0",
    title: "Albachiara",
    artist: "Vasco Rossi",
    year: "1979",
  },
  {
    id: "1R8AMI5zdplbsAtbPVsCsq",
    title: "Alghero",
    artist: "Giuni Russo",
    year: "1986",
  },
  {
    id: "5ueyLj6e6oVaTY0KQ6yLaA",
    title: "All Shook Up",
    artist: "Elvis Presley",
    year: "1958",
  },
  {
    id: "3cfOd4CMv2snFaKAnMdnvK",
    title: "All Star",
    artist: "Smash Mouth",
    year: "1999",
  },
  {
    id: "6H05BWojJmygTQQHpt9irD",
    title: "Alla Fiera Dell'Est",
    artist: "Angelo Branduardi",
    year: "1976",
  },
  {
    id: "7vc09IDmFH0MfyPYHPEWRM",
    title: "AMOR",
    artist: "Achille Lauro",
    year: "2025",
  },
  {
    id: "3JiiSo4yW8FYVnWNlvzEFO",
    title: "Amore Disperato",
    artist: "Nada",
    year: "1983",
  },
  {
    id: "7BlCLOykVzK1b6LEKP1lSB",
    title: "Ancora",
    artist: "Eduardo De Crescenzo",
    year: "1981",
  },
  {
    id: "5M8Z823Sb2BhMpecHksN0T",
    title: "ANEMA E CORE",
    artist: "Serena Brancale",
    year: "2025",
  },
  {
    id: "4AMwEGVsLR0ApxAhtN4ZQa",
    title: "Angela",
    artist: "Checco Zalone;",
    year: "2009",
  },
  {
    id: "6OVTR9jqJj6tlJiADrNq0F",
    title: "Anna E Marco",
    artist: "Lucio Dalla",
    year: "1979",
  },
  {
    id: "6dzVDS36fuRhnuIo3iLKWD",
    title: "Annare'",
    artist: "Gigi D'Alessio",
    year: "1995",
  },
  {
    id: "4gMgiXfqyzZLMhsksGmbQV",
    title: "Another Brick in the Wall",
    artist: "Pink Floyd",
    year: "1979",
  },
  {
    id: "0Bo5fjMtTfCD8vHGebivqc",
    title: "Axel F",
    artist: "Crazy Frog",
    year: "2005",
  },
  {
    id: "18IHat7huwIdEQ9hhaKfDr",
    title: "Azzurro",
    artist: "Adriano Celentano",
    year: "1968",
  },
  {
    id: "69CRrw3jmVoa4OkSjALa3f",
    title: "Ba ba baciami piccina",
    artist: "Alberto Rabagliati",
    year: "1940",
  },
  {
    id: "0SiywuOBRcynK0uKGWdCnn",
    title: "Bad Romance",
    artist: "Lady Gaga",
    year: "2009",
  },
  {
    id: "0QOFqNjkNJ8fh3yiXZieYg",
    title: "Baila",
    artist: "Zucchero ",
    year: "2001",
  },
  {
    id: "2xoVgHZKhYCmCNxqidJ4en",
    title: "Balla",
    artist: "Umberto Rosario Balsamo",
    year: "1979",
  },
  {
    id: "2LZvGSAEN2ZThkvixrHcAZ",
    title: "Balla balla ballerino",
    artist: "Lucio Dalla",
    year: "1980",
  },
  {
    id: "5mfVSsUPuBJQ5ZAakWKAP3",
    title: "Balliamo Ancora Un Po'",
    artist: "Nada",
    year: "1984",
  },
  {
    id: "6qTr4uQbPDmUghqQ6mfm48",
    title: "Balliamo sul mondo",
    artist: "Ligabue",
    year: "1990",
  },
  {
    id: "3iB8eciGU9vZkaDYkz7Ir9",
    title: "Bamboléo",
    artist: "Gipsy Kings",
    year: "1987",
  },
  {
    id: "0kzGjSRHGVcaWxagzQwAyD",
    title: "Bando",
    artist: "ANNA",
    year: "2022",
  },
  {
    id: "5pYlc1vQ6999WU43WzF4SR",
    title: "Barbra Streisand",
    artist: "Duck Sauce",
    year: "2011",
  },
  {
    id: "7laNkNLlUbNslPAi8HB1IS",
    title: "Bella senz'anima",
    artist: "Riccardo Cocciante",
    year: "1974",
  },
  {
    id: "0QlNv7zrkgYIccd7O3VzyT",
    title: "Bella Vita ",
    artist: "DJ Antoine",
    year: "2013",
  },
  {
    id: "3dZHWv3IsAQLzAr7FLJoJA",
    title: "Bello e impossibile",
    artist: "Gianna Nannini",
    year: "1986",
  },
  {
    id: "50HD75fdgIXLE6cgRLEXn5",
    title: "Berta filava",
    artist: "Rino Gaetano",
    year: "1976",
  },
  {
    id: "0odIT9B9BvOCnXfS0e4lB5",
    title: "Bette Davis Eyes",
    artist: "Kim Carnes",
    year: "1981",
  },
  {
    id: "3eAjS25afRXGFSyjPQo7l2",
    title: "Bocca di rosa",
    artist: "Fabrizio De André",
    year: "1967",
  },
  {
    id: "515XcapFOMtOOiGU31UqNp",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    year: "1975",
  },
  {
    id: "7fH13hSOyNoeiDGbjEnTUC",
    title: "Brivido",
    artist: "Guè;Marracash",
    year: "2013",
  },
  {
    id: "6sZ8y6NqtJx6xh4rFN0ggQ",
    title: "Brivido felino",
    artist: "MINACELENTANO",
    year: "1998",
  },
  {
    id: "57RGKNBUbfIBqMFEfE8CxK",
    title: "Buona sera",
    artist: "Louis Prima;",
    year: "1956",
  },
  {
    id: "3wBQw06Qv5rWbNWBnGtY07",
    title: "Buonanotte Fiorellino",
    artist: "Francesco De Gregori",
    year: "1975",
  },
  {
    id: "1f2V8U1BiWaC9aJWmpOARe",
    title: "By the way",
    artist: "Red Hot Chili Peppers",
    year: "2002",
  },
  {
    id: "08rTyeWZjwUhLcGhNupFZT",
    title: "C'era un ragazzo che come me amava i beatles e i rolling stones",
    artist: "Gianni Morandi",
    year: "1967",
  },
  {
    id: "48UPSzbZjgc449aqz8bxox",
    title: "Californication",
    artist: "Red Hot Chili Peppers",
    year: "1999",
  },
  {
    id: "6bz6uA8IhrNNvfCI4a5k3C",
    title: "Calma e sangue freddo",
    artist: "Luca Dirisio",
    year: "2004",
  },
  {
    id: "3ZOEytgrvLwQaqXreDs2Jx",
    title: "Can't Stop",
    artist: "Red Hot Chili Peppers",
    year: "2002",
  },
  {
    id: "3uNaJtGDTgZCrri8IdlAfI",
    title: "Carina",
    artist: "Fred Buscaglione",
    year: "1958",
  },
  {
    id: "0mHC3BK9vFGoEU0EcGPWRZ",
    title: "CENERE",
    artist: "Lazza",
    year: "2022",
  },
  {
    id: "1QFt5bCcWOPffwjjGBbwkC",
    title: "Centro Di Gravità Permanente",
    artist: "Franco Battiato",
    year: "1981",
  },
  {
    id: "5gTuH5Jl8PVUitsFzFslWu",
    title: "Certe notti",
    artist: "Ligabue",
    year: "1995",
  },
  {
    id: "7ob03NcaVKgs6g6QuknwTk",
    title: "Che cossè l'amor",
    artist: "Vinicio Capossela",
    year: "1994",
  },
  {
    id: "5lwcMFalrs3LfxyTI9IIuQ",
    title: "Che Rumore Fa La Felicità?",
    artist: "Negrita",
    year: "2008",
  },
  {
    id: "0hnjcFkYIjHWz0xhJeaLYr",
    title: "Che sarà",
    artist: "Ricchi e poveri",
    year: "1971",
  },
  {
    id: "5QNEUi7oFTKcOrEMzLA9uV",
    title: "Chi Non Lavora Non Fa L'Amore",
    artist: "Claudia Mori,Adriano Celentano",
    year: "1970",
  },
  {
    id: "2D6t8TtB1cpgXK1L1fJ5P5",
    title: "Chiamami Ancora Amore",
    artist: "Roberto Vecchioni",
    year: "2011",
  },
  {
    id: "4OGzwKPn6H5eR6QkAIoIdo",
    title: "Chitarratella",
    artist: "Carlo Bruti",
    year: "1938",
  },
  {
    id: "388Rzi0ggGLhG20fZnssLS",
    title: "Ciao amore, ciao",
    artist: "Luigi Tenco",
    year: "1959",
  },
  {
    id: "5zB92i6HcCHvVcX5NvGFQb",
    title: "Cinque giorni",
    artist: "Michele Zarrillo",
    year: "1994",
  },
  {
    id: "4Z0zm8QHd6ztSwAkSb6YjB",
    title: "Come è profondo il mare",
    artist: "Lucio Dalla",
    year: "1977",
  },
  {
    id: "2g3wyAWIAvmjfZ8K6Jb4Zn",
    title: "Con il nastro rosa",
    artist: "Lucio Battisti",
    year: "1980",
  },
  {
    id: "4aMT5LHe8A2uIc11H8Cx2m",
    title: "Conga",
    artist: "Gloria Estefan",
    year: "1985",
  },
  {
    id: "06hsdMbBxWGqBO0TV0Zrkf",
    title: "Cotton Eye Joe",
    artist: "Rednex",
    year: "1994",
  },
  {
    id: "0xEgDBXYO9gGzmxCFWKxNg",
    title: "CRUDELIA - I nervi",
    artist: "Marracash",
    year: "2019",
  },
  {
    id: "70H6sWVx9av1ShluLpNOJ2",
    title: "Cuccurucucù",
    artist: "Franco Battiato",
    year: "1981",
  },
  {
    id: "7gfFncgdscIxmnQ8C5Bcdj",
    title: "Da-Da-Um-Pa",
    artist: "Gemelle Kessler",
    year: "1961",
  },
  {
    id: "38uvkBIcAVfOEjC92m9A51",
    title: "Dammi solo un minuto",
    artist: "Pooh",
    year: "1977",
  },
  {
    id: "6yNxY7EaeRefxPg0g78g71",
    title: "Dance All Nite",
    artist: "Lu Colombo",
    year: "1983",
  },
  {
    id: "0GjEhVFGZW8afUYGChu3Rr",
    title: "Dancing Queen",
    artist: "Abba",
    year: "1976",
  },
  {
    id: "4DxU9yKktJVQXhcLxjh67j",
    title: "Dedicato A Te",
    artist: "Le Vibrazioni",
    year: "2003",
  },
  {
    id: "6usoB0kOZPiKbVfOZy8KHe",
    title: "Delfini (sai che c'è)",
    artist: "Domenico Modugno",
    year: "1993",
  },
  {
    id: "1Gkxhw3pozHZNEi3KvBAsa",
    title: "Dentro Alla Scatola",
    artist: "Mondo Marcio",
    year: "2006",
  },
  {
    id: "58zqNpgxzGksC3rVcnqAWk",
    title: "Diavolo In Me",
    artist: "Zucchero",
    year: "1989",
  },
  {
    id: "4xq1trF0ztWPjtwlYkqAEw",
    title: "Dieci ragazze",
    artist: "Lucio Battisti",
    year: "1970",
  },
  {
    id: "7L6ceM3HZMMRUPi8FZ1y0a",
    title: "Dio è morto",
    artist: "Nomadi",
    year: "1967",
  },
  {
    id: "008wXvCVu8W8vCbq5VQDlC",
    title: "Django",
    artist: "Luis Bacalov;Rocky Roberts",
    year: "1985",
  },
  {
    id: "1DFFUsN49AUonUcTiQNnjI",
    title: "Dolcenera",
    artist: "Fabrizio De André",
    year: "1995",
  },
  {
    id: "010XyBVMoKsb9lUqEMImak",
    title: "Don Raffaè",
    artist: "Fabrizio De André",
    year: "1990",
  },
  {
    id: "5JOVSWohrjXW0BFTboh8XO",
    title: "Don't Go",
    artist: "Yazoo",
    year: "1982",
  },
  {
    id: "4TYk0Izd7pQLdXDYxGNvyq",
    title: "Donne",
    artist: "Zucchero",
    year: "1985",
  },
  {
    id: "52Zr0sinhWTCRrQhRRY4EP",
    title: "Dragostea din tei",
    artist: "O-zone",
    year: "2003",
  },
  {
    id: "3sK8wGT43QFpWrvNQsrQya",
    title: "DtMF",
    artist: "Bad Bunny",
    year: "2025",
  },
  {
    id: "2bT6QX29M7GLSuTDSirwaS",
    title: "DÉSOLÉE",
    artist: "ANNA",
    year: "2025",
  },
  {
    id: "3xlT47mqq4g5lTCSsX0hP8",
    title: "E io ci sto",
    artist: "Rino Gaetano",
    year: "1980",
  },
  {
    id: "7IWLLvgCEy5jVnX4sy32OH",
    title: "E tu davanti a me (E tu sopra di me)",
    artist: "Erminio Sinni",
    year: "1993",
  },
  {
    id: "3AR1c3Dssq51WlGGkuYJNj",
    title: "El lado oscuro",
    artist: "Jarabe De Palo",
    year: "1996",
  },
  {
    id: "0LXXnjBrLOiGVYg5vPBIXR",
    title: "Eppur mi son scordato di te ",
    artist: "Mina",
    year: "1985",
  },
  {
    id: "2oVvW4wbCGjtAOvatvYAFu",
    title: "Eppure Sentire (un senso di te)",
    artist: "Elisa",
    year: "2006",
  },
  {
    id: "0fXVvo53LoppQI9Hx8FoOo",
    title: "Era già tutto previsto",
    artist: "Riccardo Cocciante",
    year: "1975",
  },
  {
    id: "7Co4JFHHRVoAf9lCx37aGx",
    title: "Fango in Paradiso",
    artist: "Francesca Michielin",
    year: "2025",
  },
  {
    id: "0d28khcov6AiegSCpG5TuT",
    title: "Feel Good Inc.",
    artist: "Gorillaz;De La Soul",
    year: "2005",
  },
  {
    id: "0C9rBeWAsPhmBeaYKZLN5m",
    title: "Figli Delle Stelle",
    artist: "Alan Sorrenti",
    year: "1977",
  },
  {
    id: "51Z0G9wCaGl2pcBISoJu9x",
    title: "Fiori rosa, fiori di pesco",
    artist: "Lucio Battisti",
    year: "1970",
  },
  {
    id: "5jOAhQaBlo4MsuL6pFjtli",
    title: "Firenze - Canzone triste",
    artist: "Ivan Graziani",
    year: "1980",
  },
  {
    id: "3u5N55tHf7hXATSQrjBh2q",
    title: "Freed From Desire",
    artist: "Gala;Molella;Phil Jay",
    year: "1997",
  },
  {
    id: "18NBoQ9SyURVcsPW6sP8tv",
    title: "Frosinone",
    artist: "Calcutta",
    year: "2015",
  },
  {
    id: "37yIrMPeJYRm7zJ8rr3Uvv",
    title: "Funkytown",
    artist: "Lipps Inc",
    year: "1980",
  },
  {
    id: "2oBXn8htpoyjRqrkIGGm0a",
    title: "Fuori Dal Tunnel",
    artist: "Caparezza",
    year: "2003",
  },
  {
    id: "5ara7YRzxZ27IwmPWEoNkr",
    title: "Futura",
    artist: "Lucio Dalla",
    year: "1980",
  },
  {
    id: "03UrZgTINDqvnUMbbIMhql",
    title: "Gangnam Style",
    artist: "PSY",
    year: "2012",
  },
  {
    id: "3ov7Ej1082hP2tegMtVx4L",
    title: "Gelato Al Cioccolato",
    artist: "Pupo",
    year: "1979",
  },
  {
    id: "6hwawJtSqgzNfYfLfqTv2p",
    title: "Generale",
    artist: "Francesco De Gregori",
    year: "1978",
  },
  {
    id: "5XJMc1j7M2b4l5v6fBYaNO",
    title: "giochi di gambe",
    artist: "Giorgio Poi;faccianuvola",
    year: "2025",
  },
  {
    id: "74CjS2xMK4KLnniXzFB9GI",
    title: "Gli anni",
    artist: "883",
    year: "1998",
  },
  {
    id: "35tzxthMBglBMjmZ7Fn1hj",
    title: "Gloria",
    artist: "Umberto Tozzi",
    year: "1979",
  },
  {
    id: "0PQFPcSK1gnBGlbV4CZCG0",
    title: "Good Times",
    artist: "CHIC",
    year: "1979",
  },
  {
    id: "7djxemkRcsWAqrWTye4Vxt",
    title: "Grande, grande, grande",
    artist: "Mina",
    year: "1971",
  },
  {
    id: "0pSqOevc0RI5dHLyydQSld",
    title: "Guantanamera (Guajira)",
    artist: "Zucchero",
    year: "2012",
  },
  {
    id: "5aowfqA6aFjK1FScZmg4pN",
    title: "Hanno ucciso l'Uomo Ragno",
    artist: "883",
    year: "1992",
  },
  {
    id: "3gkUxsWHTvH6jVhr3PCxLY",
    title: "Happy Hour",
    artist: "Ligabue",
    year: "2005",
  },
  {
    id: "1JO1xLtVc8mWhIoE3YaCL0",
    title: "Happy Together",
    artist: "The Turtles",
    year: "1967",
  },
  {
    id: "7CHlVPgjG1Ti7YLi09tqV8",
    title: "Ho un sassolino nella scarpa",
    artist: "Natalino Otto",
    year: "1943",
  },
  {
    id: "4aVuWgvD0X63hcOCnZtNFA",
    title: "Hold the Line",
    artist: "TOTO",
    year: "1978",
  },
  {
    id: "6Rb0ptOEjBjPPQUlQtQGbL",
    title: "Hotel Room Service",
    artist: "Pitbull",
    year: "2009",
  },
  {
    id: "46cqVRbWixI8Rc6BikLnAe",
    title: "HYPERTROIA",
    artist: "HACHIKO",
    year: "2026",
  },
  {
    id: "4h9wh7iOZ0GGn8QVp4RAOB",
    title: "I Ain't Worried",
    artist: "OneRepublic",
    year: "2022",
  },
  {
    id: "4zGBAwjlJ0TP02mHH8Wpmo",
    title: "I Love Rock N Roll",
    artist: "Joan Jett & the Blackhearts",
    year: "1981",
  },
  {
    id: "2tUBqZG2AbRi7Q0BIrVrEj",
    title: "I Wanna Dance with Somebody",
    artist: "Whitney Houston",
    year: "1987",
  },
  {
    id: "3gEO96MkIShkDIQuJRry0S",
    title: "I Want Your Love",
    artist: "CHIC",
    year: "1978",
  },
  {
    id: "3SnGymj6ijE2iuUfWxLo1q",
    title: "I'm Coming Out",
    artist: "Diana Ross",
    year: "1980",
  },
  {
    id: "0N6X297zDahWGWGDO0ulpC",
    title: "Il ballo del qua qua",
    artist: "Romina Power",
    year: "1981",
  },
  {
    id: "6oC8FuowgLT4ZSlXECLCNX",
    title: "Il ballo di San Vito",
    artist: "Vinicio Capossela",
    year: "1996",
  },
  {
    id: "2DRLmJgblGkqOwxP5OH2PR",
    title: "Il Cerchio della Vita",
    artist: "Ivana Spagna",
    year: "1994",
  },
  {
    id: "37C6DyoMu75ViTiwqxV4bY",
    title: "Il cielo in una stanza",
    artist: "Gino Paoli",
    year: "1960",
  },
  {
    id: "5ZSzAggKFjyIL6OLA2xUUg",
    title: "Il gatto e la volpe",
    artist: "Edoardo Bennato",
    year: "1977",
  },
  {
    id: "2SvXqxiG2ntfkEWvuABT7u",
    title: "Il mio canto libero",
    artist: "Lucio Battisti",
    year: "1972",
  },
  {
    id: "0i4mLwfyxnSSgF6hwIkU2L",
    title: "Il pescatore",
    artist: "Fabrizio De André",
    year: "1968",
  },
  {
    id: "5Fc7LXJHo8G333kXJRzKC7",
    title: "Il ragazzo della via Gluck",
    artist: "Adriano Celentano",
    year: "1966",
  },
  {
    id: "35eRQZmxwjgn7mQrsmtA4f",
    title: "Il Regalo Più Grande",
    artist: "Tiziano Ferro",
    year: "2008",
  },
  {
    id: "7C8kVsBSMYqmu190O2lbS5",
    title: "Il Solito Sesso",
    artist: "Max Gazzè",
    year: "2008",
  },
  {
    id: "77OdVXaJrgbXpjXscYmJRb",
    title: "In alto mare",
    artist: "Loredana Bertè",
    year: "1980",
  },
  {
    id: "09jv6S4KKCafPzreGpWcfp",
    title: "In ginocchio da te",
    artist: "Gianni Morandi",
    year: "1964",
  },
  {
    id: "1d07XYsL7hbfLrr8gnDxNr",
    title: "In questo mondo di ladri",
    artist: "Antonello Venditti",
    year: "1988",
  },
  {
    id: "60a0Rd6pjrkxjPbaKzXjfq",
    title: "In the End",
    artist: "Linkin Park",
    year: "2000",
  },
  {
    id: "19OI21O5twbekJ3xoFQ7RI",
    title: "Io come farò",
    artist: "Ornella Vanoni",
    year: "1989",
  },
  {
    id: "3KpKJkiyv02oxxSiIzKKQO",
    title: "Io Non Piango",
    artist: "Franco Califano",
    year: "1977",
  },
  {
    id: "1XZp9CsjFdnZuiNzcGYKgP",
    title: "Io vagabondo",
    artist: "Nomadi",
    year: "1972",
  },
  {
    id: "6Qyc6fS4DsZjB2mRW9DsQs",
    title: "Iris",
    artist: "The Goo Goo Dolls",
    year: "1998",
  },
  {
    id: "2IvetNzSZMH5gwjInoyr18",
    title: "It's Raining Men",
    artist: "Weather Girls",
    year: "1982",
  },
  {
    id: "4gphxUgq0JSFv2BCLhNDiE",
    title: "Jailhouse Rock",
    artist: "Elvis Presley",
    year: "1957",
  },
  {
    id: "3K0SJUQNbOkUprTFcwwAKN",
    title: "Jungle Boogie",
    artist: "Kool & The Gang",
    year: "1973",
  },
  {
    id: "6RyJ57TU2qJCw3GIv9Ag1B",
    title: "Kobra",
    artist: "Donatella Rettore",
    year: "1980",
  },
  {
    id: "1YaSQXYPqhwtw35Wf3Z0nI",
    title: "L'Amore Non Mi Basta",
    artist: "Emma",
    year: "2013",
  },
  {
    id: "39efIaQFmERjt8U71FrJzs",
    title: "L'Emozione Non Ha voce (Io Non So Parlar D'Amore)",
    artist: "Adriano Celentano",
    year: "1999",
  },
  {
    id: "116u2QIEVBnonmFpr8VqBg",
    title: "L'Era Del Cinghiale Bianco",
    artist: "Franco Battiato",
    year: "1979",
  },
  {
    id: "1eEMDXRpkipdhKj9nZliol",
    title: "L'estate sta finendo",
    artist: "Righeira",
    year: "1985",
  },
  {
    id: "57qOMZrbvnYyPRLodmnQk8",
    title: "L'isola che non c'è",
    artist: "Edoardo Bennato",
    year: "1980",
  },
  {
    id: "2S7RApTsKT0CtYojYq2cKz",
    title: "L'italiano",
    artist: "Toto Cutugno",
    year: "1983",
  },
  {
    id: "6sLvuv1jCoMzZXNvFCbDzl",
    title: "L'uccellino della comare",
    artist: "Sandra e Massimo",
    year: "1998",
  },
  {
    id: "0uMMLry3hzWGn3q3loqMkm",
    title: "La Bamba",
    artist: "Los Lobos",
    year: "1987",
  },
  {
    id: "5UmGJS0jd1r52OjnNvVHvU",
    title: "La Bomba",
    artist: "Alan Duffy",
    year: "2000",
  },
  {
    id: "5XAGVMePJNaXHcdRN578Xi",
    title: "La canzone del sole",
    artist: "Lucio Battisti",
    year: "1971",
  },
  {
    id: "0txZSVRp86nluHUhd1SbA9",
    title: "La canzone dell'amore perduto",
    artist: "Fabrizio De André",
    year: "1966",
  },
  {
    id: "6oYcyS6salzWI1ysjEScFh",
    title: "LA CODA DEL DIAVOLO (con ELODIE)",
    artist: "Rkomi;Elodie",
    year: "2021",
  },
  {
    id: "1barmMRNFXuBEWNyWvbUwI",
    title: "La collina dei ciliegi",
    artist: "Lucio Battisti",
    year: "1973",
  },
  {
    id: "7gUOmOhe5xO20Hu0bXR9SC",
    title: "La Coppia Più Bella Del Mondo",
    artist: "Adriano Celentano",
    year: "1968",
  },
  {
    id: "2T2t1DXwzdilKF3BQPHREo",
    title: "La donna cannone",
    artist: "Francesco De Gregori",
    year: "1983",
  },
  {
    id: "2LsbizbOeNa4x6qsi2jAMb",
    title: "La flaca",
    artist: "Jarabe De Palo",
    year: "1996",
  },
  {
    id: "1lNop22I4dLz5MYuc60fUX",
    title: "La guerra di Piero",
    artist: "Fabrizio De André",
    year: "1966",
  },
  {
    id: "6r8k1vznHrzlEKYxL4dZEe",
    title: "La Isla Bonita",
    artist: "Madonna",
    year: "1986",
  },
  {
    id: "2w2VPjwO34HBcWGMejcFAA",
    title: "La leva calcistica della classe '68",
    artist: "Francesco De Gregori",
    year: "1982",
  },
  {
    id: "6fB3Wy1x9EdhfFwqy8lJcZ",
    title: "La mia banda suona il Rock",
    artist: "Ivano Fossati",
    year: "1979",
  },
  {
    id: "6JuqS34gicxFr92kO7D2Hm",
    title: "La mia libertà",
    artist: "Franco Califano",
    year: "1981",
  },
  {
    id: "0kM3bPNUPgxaeOf7VzRQer",
    title: "La Mia Signorina",
    artist: "Neffa",
    year: "2001",
  },
  {
    id: "56i7VC28M9eCBRMZ5autBG",
    title: "La moto Morini",
    artist: "Mal Traa Insema",
    year: "1970",
  },
  {
    id: "7MMJa7cjMadOSR6CFWvB1x",
    title: "La musica non c'è",
    artist: "Coez",
    year: "2017",
  },
  {
    id: "49R1F3rIdSzuPk7AcHi6d1",
    title: "la noia",
    artist: "Angelina Mango",
    year: "2024",
  },
  {
    id: "2m3BCcthxDo4o4JTJ3CejS",
    title: "La paranza",
    artist: "Daniele Silvestri",
    year: "2007",
  },
  {
    id: "2TtT6prILO9coEbbbMGDjv",
    title: "La Partita Di Pallone",
    artist: "Rita Pavone",
    year: "1963",
  },
  {
    id: "4NdxkvCNQnb4w56Ytq8y8O",
    title: "La regola dell'amico",
    artist: "883",
    year: "1997",
  },
  {
    id: "4tKiqgP4hiFNSCDeoaNctg",
    title: "La sera dei miracoli",
    artist: "Lucio Dalla",
    year: "1980",
  },
  {
    id: "7eeAVOoaHu2C4zRwzoECIT",
    title: "La terra dei cachi",
    artist: "Elio e le Storie Tese",
    year: "1996",
  },
  {
    id: "0BZoZbffwUSf4cn9gdXX2S",
    title: "La tipica ragazza italiana",
    artist: "Dj Matrix",
    year: "2011",
  },
  {
    id: "2UZi7uA5vR0msMzGwFuq5f",
    title: "La vendemia",
    artist: "Daisy Lumini",
    year: "1968",
  },
  {
    id: "1mm53EPuBqamMLCr0AoCQS",
    title: "La Verità",
    artist: "Brunori Sas",
    year: "2017",
  },
  {
    id: "4kKdvXD0ez7jp1296JmAts",
    title: "Let It Snow! Let It Snow! Let It Snow!",
    artist: "Frank Sinatra;B. Swanson Quartet",
    year: "1950",
  },
  {
    id: "4hfIVhq0F0zFUcrbecsYmo",
    title: "Let's Get It Started ",
    artist: "Black Eyed Peas",
    year: "2003",
  },
  {
    id: "76pyWH7ZLr6q4kJZS3MmEE",
    title: "Live Is Life",
    artist: "Opus",
    year: "1984",
  },
  {
    id: "0Ph6L4l8dYUuXFmb71Ajnd",
    title: "Livin' la Vida Loca",
    artist: "Ricky Martin",
    year: "1999",
  },
  {
    id: "6JtY7BCKnfIlKoiglSMZhl",
    title: "Lo sto sognando",
    artist: "Checco Zalone;",
    year: "2009",
  },
  {
    id: "15JINEqzVMv3SvJTAXAKED",
    title: "Love the Way You Lie",
    artist: "Eminem;Rihanna",
    year: "2010",
  },
  {
    id: "2Jpikj1YZnA4XQYVU8yD4z",
    title: "Luci a San Siro",
    artist: "Roberto Vecchioni",
    year: "1971",
  },
  {
    id: "0vk46qEN6DEzancOurslfM",
    title: "Ma Che Freddo Fa",
    artist: "Nada",
    year: "1969",
  },
  {
    id: "5L8Rn7mlU4I5RuqUBj3MLy",
    title: "Ma guardatela",
    artist: "Edoardo Vianello",
    year: "1959",
  },
  {
    id: "1L9m2l2lhXgQ3GwmmCx3OK",
    title: "Ma il cielo è sempre più blu",
    artist: "Rino Gaetano",
    year: "1975",
  },
  {
    id: "473Vhyn1aGyuAn4s4juJB1",
    title: "Ma le gambe",
    artist: "Trio Lescano",
    year: "1938",
  },
  {
    id: "50f0mt35cIwwu3Krk7nS7b",
    title: "Ma quale idea",
    artist: "Pino D'Angiò",
    year: "1981",
  },
  {
    id: "0xRDqhYsCW6F9LM4s7gY5z",
    title: "Macho Man",
    artist: "Village People",
    year: "1978",
  },
  {
    id: "0bcrOUFQTXyJCC1lT2xfWI",
    title: "Maledetta primavera",
    artist: "Loretta Goggi",
    year: "1981",
  },
  {
    id: "2JT02CH8A8lUwB1GwqvxTQ",
    title: "Mambo Italiano",
    artist: "Renato Carosone",
    year: "1955",
  },
  {
    id: "6x4tKaOzfNJpEJHySoiJcs",
    title: "Mambo No. 5",
    artist: "Lou Bega",
    year: "1999",
  },
  {
    id: "1AsCxLAvSfilIM9ubCf89B",
    title: "Maracaibo",
    artist: "Lu Colombo",
    year: "1981",
  },
  {
    id: "5pv2bpJXi0vspHETP1QjIy",
    title: "Mare mare",
    artist: "Luca Carboni",
    year: "1991",
  },
  {
    id: "6b37xrsNCWYIUphFBazqD6",
    title: "Me Gustas Tu",
    artist: "Manu Chao",
    year: "2001",
  },
  {
    id: "4wb3UG3WkhrvjkjhlBn7dQ",
    title: "Me So' Mbriacato",
    artist: "Mannarino",
    year: "2009",
  },
  {
    id: "3F9ByoUqu31xU0I3G5xfVg",
    title: "Meet Me Halfway",
    artist: "Black Eyed Peas",
    year: "2009",
  },
  {
    id: "6wxKdEALyryMXAgyiIXmWB",
    title: "Mi manchi",
    artist: "Fausto Leali",
    year: "1988",
  },
  {
    id: "5br1K7SqSJSkL4OohYFbNl",
    title: "Mi ritorni in mente",
    artist: "Lucio Battisti",
    year: "1969",
  },
  {
    id: "1fugrphRjf2zBZWbvJwQv2",
    title: "Mi sei scoppiato dentro il cuore",
    artist: "Mina",
    year: "1966",
  },
  {
    id: "4fwR5b66ud3xUxPEUSID8q",
    title: "Mi sono innamorato di te",
    artist: "Luigi Tenco",
    year: "1962",
  },
  {
    id: "29EPnA4KRr1Eb8j835Vxqh",
    title: "Mi vendo",
    artist: "Renato Zero",
    year: "1978",
  },
  {
    id: "34E4gEdUXC7chzXMVkTyks",
    title: "Milano e Vincenzo",
    artist: "Alberto Fortis",
    year: "1979",
  },
  {
    id: "3JjZz5GolOMxBlIEKGvtWs",
    title: "Mille Lire Al Mese",
    artist: "Gilberto Mazzi",
    year: "1939",
  },
  {
    id: "6qdMhG7pRFi0csRlFGvLE4",
    title: "MILLE – feat. Orietta Berti",
    artist: "Fedez, Achille Lauro, Orietta Berti",
    year: "2021",
  },
  {
    id: "2u4pRdwTqvB0xSM3t8K2Bz",
    title: "Mio fratello è figlio unico",
    artist: "Rino Gaetano",
    year: "1976",
  },
  {
    id: "5dcyltc1ataieXIeTqhH3t",
    title: "Missili",
    artist: "Frah Quintale;Giorgio Poi",
    year: "2018",
  },
  {
    id: "4nFNJmjfgBF7jwv2oBC45b",
    title: "Money For Nothing",
    artist: "Dire Straits",
    year: "1985",
  },
  {
    id: "5TpJZQe6V0ivkwheolTSRk",
    title: "Montagne verdi",
    artist: "Marcella Bella",
    year: "1972",
  },
  {
    id: "4WpmwEdc4RBos8W8icSSxW",
    title: "Moonlight Shadow",
    artist: "Mike Oldfield",
    year: "1983",
  },
  {
    id: "0HmQkmfYXRPweIg1ycw1R8",
    title: "Morena mía",
    artist: "Miguel Bosé",
    year: "2002",
  },
  {
    id: "4UzVcXufOhGUwF56HT7b8M",
    title: "My Immortal",
    artist: "Evanescence",
    year: "2003",
  },
  {
    id: "3spdoTYpuCpmq19tuD0bOe",
    title: "My Way",
    artist: "Frank Sinatra",
    year: "1969",
  },
  {
    id: "7zrkOMlUmpdS6COxQykfVU",
    title: "Nessuno Mi Può Giudicare",
    artist: "Caterina Caselli",
    year: "1966",
  },
  {
    id: "7zrkOMlUmpdS6COxQykfVU",
    title: "Nessuno Mi Può Giudicare",
    artist: "Caterina Caselli",
    year: "1966",
  },
  {
    id: "4PTG3Z6ehGkBFwjybzWkR8",
    title: "Never Gonna Give You Up",
    artist: "Rick Astley",
    year: "1987",
  },
  {
    id: "0qemIQjSxcKyf42VPfZnfa",
    title: "Night Fever",
    artist: "Bee Gees",
    year: "1977",
  },
  {
    id: "1IkkOlYbhHxGxyxqC5nVOx",
    title: "Non dirgli mai",
    artist: "Gigi D'Alessio",
    year: "2000",
  },
  {
    id: "2YdOZTN2ElEYhEuq6zmwT8",
    title: "Non sei tu",
    artist: "Gazzelle",
    year: "2017",
  },
  {
    id: "0EOdowktdF7kczBbqstCfF",
    title: "Non so che darei",
    artist: "Alan Sorrenti",
    year: "1980",
  },
  {
    id: "5dWDWnIlasGDHFqTkfsWrm",
    title: "Non ti scordar mai di me",
    artist: "Giusy Ferreri",
    year: "2008",
  },
  {
    id: "7EOKcZX9TRkIs0nwWbCCbD",
    title: "Non è mica te",
    artist: "Eddie Brock",
    year: "2025",
  },
  {
    id: "7F54orEV7IMKtKG5X9Ig9y",
    title: "Nord sud ovest est",
    artist: "883",
    year: "1993",
  },
  {
    id: "3C31FLb0QTPyJ5GjLUUXhz",
    title: "Novembre",
    artist: "Giusy Ferreri",
    year: "2008",
  },
  {
    id: "5TFD2bmFKGhoCRbX61nXY5",
    title: "NuevaYoL",
    artist: "Bad Bunny",
    year: "2025",
  },
  {
    id: "2nLtzopw4rPReszdYBJU6h",
    title: "Numb",
    artist: "Linkin Park",
    year: "2003",
  },
  {
    id: "7JtasZPDVxx1LexFkq68R7",
    title: "Nuntereggae più",
    artist: "Rino Gaetano",
    year: "1978",
  },
  {
    id: "4EsU1itX1LEPptKwjhGbVl",
    title: "Oggi Sono Io",
    artist: "Alex Britti",
    year: "1998",
  },
  {
    id: "5xsIlITnePRLpwbGDDRDLl",
    title: "Ogni Volta",
    artist: "Paul Anka",
    year: "1964",
  },
  {
    id: "0DiWol3AO6WpXZgp0goxAV",
    title: "One More Time",
    artist: "Daft Punk",
    year: "2001",
  },
  {
    id: "64BbK9SFKH2jk86U3dGj2P",
    title: "Otherside",
    artist: "Red Hot Chili Peppers",
    year: "1999",
  },
  {
    id: "4M8filny20Mwlc2gnvtcgU",
    title: "P.E.S.",
    artist: "Club Dogo;Giuliano Palma",
    year: "2012",
  },
  {
    id: "5lmjRquEuSSRCYOBsTJRWq",
    title: "Paperella Gay",
    artist: "SpJockey;Crypto",
    year: "2016",
  },
  {
    id: "4OQ1G3dyVx0SPUzBiWCNat",
    title: "Paracetamolo",
    artist: "Calcutta",
    year: "2018",
  },
  {
    id: "72jbDTw1piOOj770jWNeaG",
    title: "Paris",
    artist: "The Chainsmokers",
    year: "2017",
  },
  {
    id: "0ty8CM0Dibp8AujC2xMWZ3",
    title: "Parlami D'Amore Mariù",
    artist: "Vittorio De Sica",
    year: "1932",
  },
  {
    id: "3gQIJcDwrN4DP05oXLQt7M",
    title: "Partiti adesso",
    artist: "Giusy Ferreri",
    year: "2017",
  },
  {
    id: "2WW9gkCVI1sqWc08I1KcBg",
    title: "Pedro",
    artist: "Raffaella Carrà",
    year: "1980",
  },
  {
    id: "5P2sVkO2mhgeDicQc1btfj",
    title: "Pensiero stupendo",
    artist: "Patty Pravo",
    year: "1978",
  },
  {
    id: "6lrlFMu06aGPDH0phlCnct",
    title: "Per dimenticare",
    artist: "Zero Assoluto",
    year: "2009",
  },
  {
    id: "5QKRTdqD7dgOIWMYXUmD6J",
    title: "Perdere l'amore",
    artist: "Massimo Ranieri",
    year: "1988",
  },
  {
    id: "0HpKuz1HfXxRzNnUqfwzgF",
    title: "Piccola stella senza cielo",
    artist: "Ligabue",
    year: "1990",
  },
  {
    id: "3PeRV7ha5XOJwsVm8SxzI7",
    title: "Pompo Nelle Casse",
    artist: "Power Francers",
    year: "2012",
  },
  {
    id: "2fTsFCKRFQ5M0igJgabnLA",
    title: "Price Tag",
    artist: "Jessie J",
    year: "2011",
  },
  {
    id: "0HQf0bd3oSZei450iKuUFR",
    title: "Prisencolinensinainciusol",
    artist: "Adriano Celentano",
    year: "1973",
  },
  {
    id: "2pKsnZaXSTmGQKPAkPuJfv",
    title: "Puppe a pera - Live",
    artist: "Cecco e Cipo",
    year: "2017",
  },
  {
    id: "5NVKrGAZjusEqZJ7onT9gO",
    title: "Quando, Quando, Quando",
    artist: "Tony Renis",
    year: "1963",
  },
  {
    id: "7zelsfhR5SxQRSTXsjatoW",
    title: "Quant'è bello lu primmo ammore",
    artist: "Tony Santagata",
    year: "1974",
  },
  {
    id: "0Oj0nsrBu8YrJdR84VWJV0",
    title: "Quarantaquattro gatti",
    artist: "Piccolo Coro dell'Antoniano;Zecchino d'Oro",
    year: "1996",
  },
  {
    id: "0x3reuFIL9WfzDdzoigr8p",
    title: "Ragazzo Fortunato",
    artist: "Jovanotti",
    year: "1992",
  },
  {
    id: "7MKcM6TfaGKQVFfhstCbOw",
    title: "Redemption Song",
    artist: "Bob Marley & The Wailers",
    year: "1980",
  },
  {
    id: "0NAjpcNOjROBcwFNQlcXY9",
    title: "Ricominciamo",
    artist: "Adriano Pappalardo",
    year: "1998",
  },
  {
    id: "515XcapFOMtOOiGU31UqNp",
    title: "Rimmel",
    artist: "Francesco De Gregori",
    year: "1975",
  },
  {
    id: "1VpEzp0VfgywKm4nlbouTM",
    title: "Roma capoccia",
    artist: "Antonello Venditti",
    year: "1972",
  },
  {
    id: "1nLGeFQuY7PFxrou3ezEvP",
    title: "Rossetto e caffè",
    artist: "Sal Da Vinci",
    year: "2024",
  },
  {
    id: "0xYkr8xRLT8vbFA1yrSYO1",
    title: "Rotolando Verso Sud",
    artist: "Negrita",
    year: "2005",
  },
  {
    id: "7rbqd5c7Fg1CdLqQRab4YO",
    title: "Salirò",
    artist: "Daniele Silvestri",
    year: "2002",
  },
  {
    id: "4hJSzUREpdDo8uhgEflbHr",
    title: "Sally",
    artist: "Vasco Rossi",
    year: "1996",
  },
  {
    id: "4JhVT1nbnp9eyIU70mUqot",
    title: "Samarcanda",
    artist: "Roberto Vecchioni ",
    year: "1977",
  },
  {
    id: "3DAFQyYYpTDEuChTS8eTU7",
    title: "Sapore di Sale",
    artist: "Gino Paoli",
    year: "1963",
  },
  {
    id: "6lK2xptPzLPmvpE29U4mDH",
    title: "Sarà perché ti amo",
    artist: "Ricchi e poveri",
    year: "1981",
  },
  {
    id: "2PzU4IB8Dr6mxV3lHuaG34",
    title: "Satisfaction",
    artist: "Rolling Stones",
    year: "1965",
  },
  {
    id: "1G391cbiT3v3Cywg8T7DM1",
    title: "Scar Tissue",
    artist: "Red Hot Chili Peppers",
    year: "1999",
  },
  {
    id: "0wP3e5PzSxafy2TRtlayq9",
    title: "Scatman (ski-ba-bop-ba-dop-bop)",
    artist: "Scatman John",
    year: "1994",
  },
  {
    id: "7Djndakc0nj5PcKpF8Z67p",
    title: "Se bruciasse la città",
    artist: "Massimo Ranieri",
    year: "1970",
  },
  {
    id: "3Qjr2mNDOn24M4Y50hR9hJ",
    title: "Se mi lasci non vale",
    artist: "Julio Iglesias",
    year: "1976",
  },
  {
    id: "2bYLru2w0NKtCDiFPgALFE",
    title: "Se telefonando",
    artist: "Mina",
    year: "1966",
  },
  {
    id: "4g6BNLYlAei2bppoe5Z3gK",
    title: "Sei ottavi",
    artist: "Rino Gaetano",
    year: "1977",
  },
  {
    id: "42FUNUTTu4dhDhca834rd6",
    title: "Self Control",
    artist: "Raf",
    year: "1984",
  },
  {
    id: "6gwLtpIJ9xpgu37Nk0O7hy",
    title: "Sentimento Pentimento",
    artist: "Neri per Caso",
    year: "1995",
  },
  {
    id: "3ShEGKdskF0ke7iW2u9gjD",
    title: "Senza Una Donna",
    artist: "Zucchero",
    year: "1987",
  },
  {
    id: "3kXoKlD84c6OmIcOLfrfEs",
    title: "September",
    artist: "Earth, Wind & Fire",
    year: "1978",
  },
  {
    id: "4Ovy5UkvkweOluGd9hoKsR",
    title: "Sere nere",
    artist: "Tiziano Ferro",
    year: "2003",
  },
  {
    id: "3dPQuX8Gs42Y7b454ybpMR",
    title: "Seven Nation Army",
    artist: "The White Stripes",
    year: "2003",
  },
  {
    id: "2VxeLyX666F8uXCJ0dZF8B",
    title: "Shallow",
    artist: "Lady Gaga, Bradley Cooper",
    year: "2018",
  },
  {
    id: "0CuTlmtd8SLVMzzEWcet3B",
    title: "Siamo Una Squadra Fortissimi",
    artist: "Siamo Una Squadra Fo",
    year: "2007",
  },
  {
    id: "4CeeEOM32jQcH3eN9Q2dGj",
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    year: "1991",
  },
  {
    id: "2bCQHF9gdG5BNDVuEIEnNk",
    title: "Smooth Criminalr",
    artist: "Michael Jackson ",
    year: "1987",
  },
  {
    id: "2aibwv5hGXSgw7Yru8IYTO",
    title: "Snow",
    artist: "Red Hot Chili Peppers",
    year: "2006",
  },
  {
    id: "2Nf0v3mlQYMMOQZV0aAlNQ",
    title: "Soli",
    artist: "Toto Cutugno",
    year: "1979",
  },
  {
    id: "62oaDoBveZxvZb94ziiMXi",
    title: "Somebody That I Used to Know",
    artist: "Gotye",
    year: "2011",
  },
  {
    id: "63653pPBcMFICrM0PByMOG",
    title: "Sono solo Canzonette",
    artist: "Edoardo Bennato",
    year: "1980",
  },
  {
    id: "4SjRtuCDZvO68N2agNkahv",
    title: "Sono solo parole",
    artist: "Noemi",
    year: "2011",
  },
  {
    id: "28VLTrPaxvmNfeouDsUkll",
    title: "Sotto Casa",
    artist: "Max Gazzè",
    year: "2013",
  },
  {
    id: "1NuO0tyBz42QOelnFbDHPD",
    title: "Sotto questo sole",
    artist: "Francesco Baccini",
    year: "1990",
  },
  {
    id: "1dEZlviHVC2Sbm4TmFnmWK",
    title: "Spendi spandi effendi",
    artist: "Rino Gaetano",
    year: "1977",
  },
  {
    id: "5CQ30WqJwcep0pYcV4AMNc",
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    year: "1971",
  },
  {
    id: "3SdTKo2uVsxFblQjpScoHy",
    title: "Stand By Me",
    artist: "Ben E. King",
    year: "1962",
  },
  {
    id: "0pQskrTITgmCMyr85tb9qq",
    title: "Starman",
    artist: "David Bowie",
    year: "1972",
  },
  {
    id: "7uZF6CYmfNQ2lqRYqDhSdc",
    title: "Stasera mi butto",
    artist: "Rocky Roberts",
    year: "1967",
  },
  {
    id: "4UDmDIqJIbrW0hMBQMFOsM",
    title: "Stayin' Alive",
    artist: "Bee Gees",
    year: "1977",
  },
  {
    id: "0NUyAEi7WInhF0SJGVavUG",
    title: "Stella Stai",
    artist: "Umberto Tozzi",
    year: "1980",
  },
  {
    id: "6Ahg1hncxUdK0ICqU03BCu",
    title: "Superclassico",
    artist: "Ernia",
    year: "2020",
  },
  {
    id: "1TGbX9T3ijObYeak790FSe",
    title: "Supponiamo un amore",
    artist: "Rino Gaetano",
    year: "1974",
  },
  {
    id: "2dbaIpJoAk2hhrrX2ljKJo",
    title: "Surfin' U.S.A.",
    artist: "The Beach Boys",
    year: "1963",
  },
  {
    id: "6oWLiyRpo1ibp2vKNxHG0T",
    title: "Sweet Dreams",
    artist: "Eurythmics ",
    year: "1983",
  },
  {
    id: "7e89621JPkKaeDSTQ3avtg",
    title: "Sweet Home Alabama",
    artist: "Lynyrd Skynyrd",
    year: "1974",
  },
  {
    id: "6EhPXpRYkwGwg8lx3XiGTI",
    title: "Tacata",
    artist: "Tacabro",
    year: "2012",
  },
  {
    id: "3dYD57lRAUcMHufyqn9GcI",
    title: "Take Me To Church",
    artist: "Hozier",
    year: "2013",
  },
  {
    id: "15MJ5NThPjj6xhPcts8MiY",
    title: "Take My Breath Away",
    artist: "Berlin",
    year: "1986",
  },
  {
    id: "3ZqL7rtfHLxWk7PQnZv7hH",
    title: "Tanto pè cantà",
    artist: "Nino Manfredi",
    year: "1932",
  },
  {
    id: "67wVRCHjobnBE40XNlBVGP",
    title: "Tappeto di fragole",
    artist: "Modà",
    year: "2011",
  },
  {
    id: "58uxzfDiTqLqEfNyO3ch21",
    title: "Tex-Mex",
    artist: "Mina;Ivano Fossati",
    year: "2019",
  },
  {
    id: "5HOpkTTVcmZHnthgyxrIL8",
    title: "The Fox",
    artist: "Ylvis",
    year: "2013",
  },
  {
    id: "3yfqSUWxFvZELEM4PmlwIR",
    title: "The Real Slim Shady",
    artist: "Eminem",
    year: "2000",
  },
  {
    id: "3S2R0EVwBSAVMd5UMgKTL0",
    title: "Thriller",
    artist: "Michael Jackson",
    year: "1982",
  },
  {
    id: "0gAbf0NL9no1Urk1Wj8Uui",
    title: "Ti Amo",
    artist: "Umberto Tozzi",
    year: "1977",
  },
  {
    id: "1aIMyZUrzSkRXJgYO0XO3R",
    title: "Ti Fa Stare Bene",
    artist: "Caparezza",
    year: "2017",
  },
  {
    id: "52lYqr81fi0H2yVLupzGwy",
    title: "Ti regalerò una rosa",
    artist: "Simone Cristicchi",
    year: "2007",
  },
  {
    id: "2IDNV0ttledZreT0JtzFMp",
    title: "Ti scatterò una foto",
    artist: "Tiziano Ferro",
    year: "2006",
  },
  {
    id: "3cHyrEgdyYRjgJKSOiOtcS",
    title: "Timber",
    artist: "Pitbull",
    year: "2013",
  },
  {
    id: "1IHWl5LamUGEuP4ozKQSXZ",
    title: "Tití Me Preguntó",
    artist: "Bad Bunny",
    year: "2022",
  },
  {
    id: "4hv9MeB0ZuzbFFThnQqLPC",
    title: "Trinity ",
    artist: "Annibale",
    year: "1970",
  },
  {
    id: "4q2lRiodoQnyFO65watkse",
    title: "True",
    artist: "Spandau Ballet",
    year: "1983",
  },
  {
    id: "5ez6STfeeuCyahjmGFmudi",
    title: "Tu vuo' fa l'americano",
    artist: "Renato Carosone",
    year: "1956",
  },
  {
    id: "3425P4GkmTIF4d5fVETZvZ",
    title: "Tuca Tuca",
    artist: "Raffaella Carrà",
    year: "1971",
  },
  {
    id: "0RbhVoxOZE8BniSgmDbaXV",
    title: "Tutto il resto e' noia",
    artist: "Franco Califano",
    year: "1976",
  },
  {
    id: "7eAEs2SiV7DtS8b13PGXWZ",
    title: "Un bacio a mezzanotte",
    artist: "Quartetto Cetra",
    year: "1945",
  },
  {
    id: "4ONboWX5n2926t6TcJEGHh",
    title: "un estate al mare",
    artist: "Giuni Russo",
    year: "1982",
  },
  {
    id: "7B09xj4jnG1763TWkVxazM",
    title: "Un'avventura",
    artist: "Lucio Battisti",
    year: "1969",
  },
  {
    id: "3MxghkgO8EVfMQAnUFH0Iu",
    title: "Un'emozione da poco",
    artist: "Anna Oxa",
    year: "1978",
  },
  {
    id: "6oyYKWTbYt5Zb8tIiLZbmH",
    title: "Unchain My Heart",
    artist: "Joe Cocker",
    year: "1987",
  },
  {
    id: "3d9DChrdc6BOeFsbrZ3Is0",
    title: "Under the Bridge",
    artist: "Red Hot Chili Peppers",
    year: "1992",
  },
  {
    id: "6XpjIhIhIA5AGTyk06FNKU",
    title: "Uomini soli",
    artist: "Pooh",
    year: "1990",
  },
  {
    id: "3pbtBomO4Zt5gGiqsYeiBH",
    title: "Upside Down",
    artist: "Diana Ross",
    year: "1980",
  },
  {
    id: "2tNiJQG6eaLT9y1pqdj5VV",
    title: "Vacanze Romane",
    artist: "Matia Bazar",
    year: "1983",
  },
  {
    id: "0rHIXD2GmjixirvBfTUV2b",
    title: "Vecchio frack",
    artist: "Domenico Modugno",
    year: "1955",
  },
  {
    id: "7DUs0muJGnpQ4g8N4xC35S",
    title: "Vengo Anch'io No tu No",
    artist: "Enzo Jannacci",
    year: "1967",
  },
  {
    id: "424BQDJzOJqfJCZusTvAZP",
    title: "Vengo Dalla Luna",
    artist: "Caparezza",
    year: "2003",
  },
  {
    id: "7IBGw13AbUorsu133u6Q0Z",
    title: "Vieni A Ballare In Puglia",
    artist: "Caparezza",
    year: "2008",
  },
  {
    id: "5HWaf9xEiclGk3usOlE2Ex",
    title: "Viva la pappa col pomodoro",
    artist: "Rita Pavone",
    year: "1964",
  },
  {
    id: "6WVSjBksHbfBVhvZew41iY",
    title: "VOCE",
    artist: "Madame",
    year: "2021",
  },
  {
    id: "2srhl7uP5M5uvtG9sQoLSe",
    title: "Vola colomba",
    artist: "Nilla Pizzi",
    year: "1952",
  },
  {
    id: "0vzjqLeM8F95Y7uYPVkESU",
    title: "Volevo te",
    artist: "Giusy Ferreri",
    year: "2015",
  },
  {
    id: "5Hk4Mpex0s2ndUpDQ5v2rU",
    title: "Walk of Life",
    artist: "Dire Straits",
    year: "1985",
  },
  {
    id: "1Je1IMUlBXcx1Fz0WE7oPT",
    title: "Wannabe",
    artist: "Spice Girls",
    year: "1996",
  },
  {
    id: "0xmjwnQ3FNE6HuWCt2nHdZ",
    title: "Where Is The Love?",
    artist: "Black Eyed Peas",
    year: "2003",
  },
  {
    id: "6mFkJmJqdDVQ1REhVfGgd1",
    title: "Wish you were Here",
    artist: "Pink Floyd",
    year: "1975",
  },
  {
    id: "3h0v8BiwP1qzlCX7TXrsDF",
    title: "Xdono",
    artist: "Tiziano Ferro",
    year: "2001",
  },
  {
    id: "54OR1VDpfkBuOY5zZjhZAY",
    title: "YMCA",
    artist: "Village People",
    year: "1978",
  },
  {
    id: "4kzOYNpDNmkSGs9w6Z7dVB",
    title: "Zingara",
    artist: "Iva Zanicchi",
    year: "1970",
  },
];
