window.SONGS = [
  {
    id: "4g7ASoGYRujjvNL6DHX9j8",
    durationMs: 137853,
    title: "24.000 Baci",
    artist: "Adriano Celentano",
    year: "1961",
  },
  {
    id: "3yGyWqmw9eCQPdJJ6iJLWs",
    durationMs: 222634,
    title: "4/3/1943",
    artist: "Lucio Dalla",
    year: "1971",
  },
  {
    id: "3q3hFN65AWi7IjVwxN6juk",
    durationMs: 226080,
    title: "46",
    artist: "Cesare Cremonini",
    year: "2015",
  },
  {
    id: "0x4HvQuUbXAa4bYForAK7S",
    durationMs: 218506,
    title: "A mano a mano",
    artist: "Rino Gaetano",
    year: "1981",
  },
  {
    id: "7rl7TNsfJiJJ3BY47peVSm",
    durationMs: 271360,
    title: "A un passo da te",
    artist: "MINACELENTANO",
    year: "2016",
  },
  {
    id: "7EM7aTxoicXDjIy3gK6Pnu",
    durationMs: 230093,
    title: "A Volte Esagero",
    artist: "Marracash;Salmo;Coez",
    year: "2015",
  },
  {
    id: "6DaqDhzDgtIPLeowS4N3kA",
    durationMs: 166164,
    title: "Abbracciami",
    artist: "Marino marini",
    year: "1958",
  },
  {
    id: "1N46SW28bpacvXmNYP6PTB",
    durationMs: 214421,
    title: "Acqua azzurra, acqua chiara",
    artist: "Lucio Battisti",
    year: "1969",
  },
  {
    id: "1e4ZMHWU3wxRzeDtfITbhT",
    durationMs: 282360,
    title: "Acqua e sale",
    artist: "MINACELENTANO",
    year: "1998",
  },
  {
    id: "5IfoBzoixewbULHm5mHLJZ",
    durationMs: 272840,
    title: "Acqua e Sapone",
    artist: "Stadio",
    year: "1983",
  },
  {
    id: "0uhbLe0AwiGMBcFGk3fI6x",
    durationMs: 254677,
    title: "Ad esempio a me piace il sud",
    artist: "Rino Gaetano",
    year: "1974",
  },
  {
    id: "6sKdsm15cungJazNyWHdOE",
    durationMs: 213026,
    title: "Adelante! Adelante!",
    artist: "Francesco De Gregori",
    year: "1992",
  },
  {
    id: "0INaMqjJJe1BZpnWuCxDzt",
    durationMs: 170893,
    title: "Ai Se Eu Te Pego",
    artist: "Michel Teló",
    year: "2011",
  },
  {
    id: "7N1SQcqAkSvUgnlvrU0Et8",
    durationMs: 264021,
    title: "Aida",
    artist: "Rino Gaetano",
    year: "1977",
  },
  {
    id: "53MYtv4tzLYg1hbu13Qbc0",
    durationMs: 245533,
    title: "Albachiara",
    artist: "Vasco Rossi",
    year: "1979",
  },
  {
    id: "1R8AMI5zdplbsAtbPVsCsq",
    durationMs: 245524,
    title: "Alghero",
    artist: "Giuni Russo",
    year: "1986",
  },
  {
    id: "5ueyLj6e6oVaTY0KQ6yLaA",
    durationMs: 119837,
    title: "All Shook Up",
    artist: "Elvis Presley",
    year: "1957",
  },
  {
    id: "3cfOd4CMv2snFaKAnMdnvK",
    durationMs: 200373,
    title: "All Star",
    artist: "Smash Mouth",
    year: "1999",
  },
  {
    id: "6H05BWojJmygTQQHpt9irD",
    durationMs: 322840,
    title: "Alla Fiera Dell'Est",
    artist: "Angelo Branduardi",
    year: "1976",
  },
  {
    id: "7vc09IDmFH0MfyPYHPEWRM",
    durationMs: 177348,
    title: "AMOR",
    artist: "Achille Lauro",
    year: "2025",
  },
  {
    id: "3JiiSo4yW8FYVnWNlvzEFO",
    durationMs: 240760,
    title: "Amore Disperato",
    artist: "Nada",
    year: "1983",
  },
  {
    id: "7BlCLOykVzK1b6LEKP1lSB",
    durationMs: 203000,
    title: "Ancora",
    artist: "Eduardo De Crescenzo",
    year: "1981",
  },
  {
    id: "5M8Z823Sb2BhMpecHksN0T",
    durationMs: 166611,
    title: "ANEMA E CORE",
    artist: "Serena Brancale",
    year: "2025",
  },
  {
    id: "4AMwEGVsLR0ApxAhtN4ZQa",
    durationMs: 194600,
    title: "Angela",
    artist: "Checco Zalone;",
    year: "2009",
  },
  {
    id: "6OVTR9jqJj6tlJiADrNq0F",
    durationMs: 221093,
    title: "Anna E Marco",
    artist: "Lucio Dalla",
    year: "1979",
  },
  {
    id: "6dzVDS36fuRhnuIo3iLKWD",
    durationMs: 280272,
    title: "Annare'",
    artist: "Gigi D'Alessio",
    year: "1995",
  },
  {
    id: "4gMgiXfqyzZLMhsksGmbQV",
    durationMs: 238946,
    title: "Another Brick in the Wall",
    artist: "Pink Floyd",
    year: "1979",
  },
  {
    id: "0Bo5fjMtTfCD8vHGebivqc",
    durationMs: 171739,
    title: "Axel F",
    artist: "Crazy Frog",
    year: "2005",
  },
  {
    id: "18IHat7huwIdEQ9hhaKfDr",
    durationMs: 221120,
    title: "Azzurro",
    artist: "Adriano Celentano",
    year: "1968",
  },
  {
    id: "69CRrw3jmVoa4OkSjALa3f",
    durationMs: 172186,
    title: "Ba ba baciami piccina",
    artist: "Alberto Rabagliati",
    year: "1940",
  },
  {
    id: "0SiywuOBRcynK0uKGWdCnn",
    durationMs: 294573,
    title: "Bad Romance",
    artist: "Lady Gaga",
    year: "2009",
  },
  {
    id: "0QOFqNjkNJ8fh3yiXZieYg",
    durationMs: 246840,
    title: "Baila",
    artist: "Zucchero",
    year: "2001",
  },
  {
    id: "2xoVgHZKhYCmCNxqidJ4en",
    durationMs: 195333,
    title: "Balla",
    artist: "Umberto Rosario Balsamo",
    year: "1979",
  },
  {
    id: "2LZvGSAEN2ZThkvixrHcAZ",
    durationMs: 347866,
    title: "Balla balla ballerino",
    artist: "Lucio Dalla",
    year: "1980",
  },
  {
    id: "5mfVSsUPuBJQ5ZAakWKAP3",
    durationMs: 218933,
    title: "Balliamo Ancora Un Po'",
    artist: "Nada",
    year: "1984",
  },
  {
    id: "6qTr4uQbPDmUghqQ6mfm48",
    durationMs: 274626,
    title: "Balliamo sul mondo",
    artist: "Ligabue",
    year: "1990",
  },
  {
    id: "3iB8eciGU9vZkaDYkz7Ir9",
    durationMs: 203333,
    title: "Bamboléo",
    artist: "Gipsy Kings",
    year: "1987",
  },
  {
    id: "0kzGjSRHGVcaWxagzQwAyD",
    durationMs: 168000,
    title: "Bando",
    artist: "ANNA",
    year: "2020",
  },
  {
    id: "5pYlc1vQ6999WU43WzF4SR",
    durationMs: 194531,
    title: "Barbra Streisand",
    artist: "Duck Sauce",
    year: "2010",
  },
  {
    id: "7laNkNLlUbNslPAi8HB1IS",
    durationMs: 274973,
    title: "Bella senz'anima",
    artist: "Riccardo Cocciante",
    year: "1974",
  },
  {
    id: "0QlNv7zrkgYIccd7O3VzyT",
    durationMs: 203820,
    title: "Bella Vita",
    artist: "DJ Antoine",
    year: "2013",
  },
  {
    id: "3dZHWv3IsAQLzAr7FLJoJA",
    durationMs: 282973,
    title: "Bello e impossibile",
    artist: "Gianna Nannini",
    year: "1986",
  },
  {
    id: "50HD75fdgIXLE6cgRLEXn5",
    durationMs: 219392,
    title: "Berta filava",
    artist: "Rino Gaetano",
    year: "1976",
  },
  {
    id: "0odIT9B9BvOCnXfS0e4lB5",
    durationMs: 228000,
    title: "Bette Davis Eyes",
    artist: "Kim Carnes",
    year: "1981",
  },
  {
    id: "3eAjS25afRXGFSyjPQo7l2",
    durationMs: 185386,
    title: "Bocca di rosa",
    artist: "Fabrizio De André",
    year: "1967",
  },
  {
    id: "4u7EnebtmKWzUH433cf5Qv",
    durationMs: 354320,
    title: "Bohemian Rhapsody",
    artist: "Queen",
    year: "1975",
  },
  {
    id: "7fH13hSOyNoeiDGbjEnTUC",
    durationMs: 227693,
    title: "Brivido",
    artist: "Guè;Marracash",
    year: "2013",
  },
  {
    id: "6sZ8y6NqtJx6xh4rFN0ggQ",
    durationMs: 224466,
    title: "Brivido felino",
    artist: "MINACELENTANO",
    year: "1998",
  },
  {
    id: "57RGKNBUbfIBqMFEfE8CxK",
    durationMs: 186034,
    title: "Buona sera",
    artist: "Louis Prima;",
    year: "1956",
  },
  {
    id: "3wBQw06Qv5rWbNWBnGtY07",
    durationMs: 125040,
    title: "Buonanotte Fiorellino",
    artist: "Francesco De Gregori",
    year: "1975",
  },
  {
    id: "1f2V8U1BiWaC9aJWmpOARe",
    durationMs: 216933,
    title: "By the way",
    artist: "Red Hot Chili Peppers",
    year: "2002",
  },
  {
    id: "08rTyeWZjwUhLcGhNupFZT",
    durationMs: 196986,
    title: "C'era un ragazzo che come me amava i beatles e i rolling stones",
    artist: "Gianni Morandi",
    year: "1967",
  },
  {
    id: "48UPSzbZjgc449aqz8bxox",
    durationMs: 329733,
    title: "Californication",
    artist: "Red Hot Chili Peppers",
    year: "1999",
  },
  {
    id: "6bz6uA8IhrNNvfCI4a5k3C",
    durationMs: 208146,
    title: "Calma e sangue freddo",
    artist: "Luca Dirisio",
    year: "2004",
  },
  {
    id: "3ZOEytgrvLwQaqXreDs2Jx",
    durationMs: 269000,
    title: "Can't Stop",
    artist: "Red Hot Chili Peppers",
    year: "2002",
  },
  {
    id: "3uNaJtGDTgZCrri8IdlAfI",
    durationMs: 144813,
    title: "Carina",
    artist: "Fred Buscaglione",
    year: "1958",
  },
  {
    id: "0mHC3BK9vFGoEU0EcGPWRZ",
    durationMs: 208323,
    title: "CENERE",
    artist: "Lazza",
    year: "2022",
  },
  {
    id: "1QFt5bCcWOPffwjjGBbwkC",
    durationMs: 232932,
    title: "Centro Di Gravità Permanente",
    artist: "Franco Battiato",
    year: "1981",
  },
  {
    id: "5gTuH5Jl8PVUitsFzFslWu",
    durationMs: 261398,
    title: "Certe notti",
    artist: "Ligabue",
    year: "1995",
  },
  {
    id: "7ob03NcaVKgs6g6QuknwTk",
    durationMs: 254141,
    title: "Che cossè l'amor",
    artist: "Vinicio Capossela",
    year: "1994",
  },
  {
    id: "5lwcMFalrs3LfxyTI9IIuQ",
    durationMs: 270946,
    title: "Che Rumore Fa La Felicità?",
    artist: "Negrita",
    year: "2008",
  },
  {
    id: "0hnjcFkYIjHWz0xhJeaLYr",
    durationMs: 184880,
    title: "Che sarà",
    artist: "Ricchi e poveri",
    year: "1971",
  },
  {
    id: "5QNEUi7oFTKcOrEMzLA9uV",
    durationMs: 178626,
    title: "Chi Non Lavora Non Fa L'Amore",
    artist: "Claudia Mori,Adriano Celentano",
    year: "1970",
  },
  {
    id: "2D6t8TtB1cpgXK1L1fJ5P5",
    durationMs: 253986,
    title: "Chiamami Ancora Amore",
    artist: "Roberto Vecchioni",
    year: "2011",
  },
  {
    id: "4OGzwKPn6H5eR6QkAIoIdo",
    durationMs: 198600,
    title: "Chitarratella",
    artist: "Carlo Buti",
    year: "1938",
  },
  {
    id: "388Rzi0ggGLhG20fZnssLS",
    durationMs: 184093,
    title: "Ciao amore, ciao",
    artist: "Luigi Tenco",
    year: "1967",
  },
  {
    id: "5zB92i6HcCHvVcX5NvGFQb",
    durationMs: 249760,
    title: "Cinque giorni",
    artist: "Michele Zarrillo",
    year: "1994",
  },
  {
    id: "4Z0zm8QHd6ztSwAkSb6YjB",
    durationMs: 321160,
    title: "Come è profondo il mare",
    artist: "Lucio Dalla",
    year: "1977",
  },
  {
    id: "2g3wyAWIAvmjfZ8K6Jb4Zn",
    durationMs: 321097,
    title: "Con il nastro rosa",
    artist: "Lucio Battisti",
    year: "1980",
  },
  {
    id: "4aMT5LHe8A2uIc11H8Cx2m",
    durationMs: 255106,
    title: "Conga",
    artist: "Gloria Estefan",
    year: "1985",
  },
  {
    id: "06hsdMbBxWGqBO0TV0Zrkf",
    durationMs: 194000,
    title: "Cotton Eye Joe",
    artist: "Rednex",
    year: "1994",
  },
  {
    id: "0xEgDBXYO9gGzmxCFWKxNg",
    durationMs: 230922,
    title: "CRUDELIA - I nervi",
    artist: "Marracash",
    year: "2019",
  },
  {
    id: "70H6sWVx9av1ShluLpNOJ2",
    durationMs: 253093,
    title: "Cuccurucucù",
    artist: "Franco Battiato",
    year: "1981",
  },
  {
    id: "7gfFncgdscIxmnQ8C5Bcdj",
    durationMs: 137506,
    title: "Da-Da-Um-Pa",
    artist: "Gemelle Kessler",
    year: "1961",
  },
  {
    id: "38uvkBIcAVfOEjC92m9A51",
    durationMs: 275013,
    title: "Dammi solo un minuto",
    artist: "Pooh",
    year: "1977",
  },
  {
    id: "6yNxY7EaeRefxPg0g78g71",
    durationMs: 224320,
    title: "Dance All Nite",
    artist: "Lu Colombo",
    year: "1983",
  },
  {
    id: "0GjEhVFGZW8afUYGChu3Rr",
    durationMs: 230400,
    title: "Dancing Queen",
    artist: "Abba",
    year: "1976",
  },
  {
    id: "4DxU9yKktJVQXhcLxjh67j",
    durationMs: 208466,
    title: "Dedicato A Te",
    artist: "Le Vibrazioni",
    year: "2003",
  },
  {
    id: "6usoB0kOZPiKbVfOZy8KHe",
    durationMs: 278346,
    title: "Delfini (sai che c'è)",
    artist: "Domenico Modugno",
    year: "1993",
  },
  {
    id: "1Gkxhw3pozHZNEi3KvBAsa",
    durationMs: 264266,
    title: "Dentro Alla Scatola",
    artist: "Mondo Marcio",
    year: "2006",
  },
  {
    id: "58zqNpgxzGksC3rVcnqAWk",
    durationMs: 243066,
    title: "Diavolo In Me",
    artist: "Zucchero",
    year: "1989",
  },
  {
    id: "4xq1trF0ztWPjtwlYkqAEw",
    durationMs: 177023,
    title: "Dieci ragazze",
    artist: "Lucio Battisti",
    year: "1970",
  },
  {
    id: "7L6ceM3HZMMRUPi8FZ1y0a",
    durationMs: 173973,
    title: "Dio è morto",
    artist: "Nomadi",
    year: "1967",
  },
  {
    id: "008wXvCVu8W8vCbq5VQDlC",
    durationMs: 173693,
    title: "Django",
    artist: "Luis Bacalov;Rocky Roberts",
    year: "1966",
  },
  {
    id: "1DFFUsN49AUonUcTiQNnjI",
    durationMs: 297786,
    title: "Dolcenera",
    artist: "Fabrizio De André",
    year: "1996",
  },
  {
    id: "010XyBVMoKsb9lUqEMImak",
    durationMs: 248653,
    title: "Don Raffaè",
    artist: "Fabrizio De André",
    year: "1990",
  },
  {
    id: "5JOVSWohrjXW0BFTboh8XO",
    durationMs: 188466,
    title: "Don't Go",
    artist: "Yazoo",
    year: "1982",
  },
  {
    id: "4TYk0Izd7pQLdXDYxGNvyq",
    durationMs: 215706,
    title: "Donne",
    artist: "Zucchero",
    year: "1985",
  },
  {
    id: "52Zr0sinhWTCRrQhRRY4EP",
    durationMs: 215386,
    title: "Dragostea din tei",
    artist: "O-zone",
    year: "2003",
  },
  {
    id: "3sK8wGT43QFpWrvNQsrQya",
    durationMs: 237117,
    title: "DtMF",
    artist: "Bad Bunny",
    year: "2025",
  },
  {
    id: "2bT6QX29M7GLSuTDSirwaS",
    durationMs: 159000,
    title: "DÉSOLÉE",
    artist: "ANNA",
    year: "2025",
  },
  {
    id: "3xlT47mqq4g5lTCSsX0hP8",
    durationMs: 244394,
    title: "E io ci sto",
    artist: "Rino Gaetano",
    year: "1980",
  },
  {
    id: "7IWLLvgCEy5jVnX4sy32OH",
    durationMs: 310466,
    title: "E tu davanti a me (E tu sopra di me)",
    artist: "Erminio Sinni",
    year: "1993",
  },
  {
    id: "3AR1c3Dssq51WlGGkuYJNj",
    durationMs: 288053,
    title: "El lado oscuro",
    artist: "Jarabe De Palo",
    year: "1996",
  },
  {
    id: "0LXXnjBrLOiGVYg5vPBIXR",
    durationMs: 229600,
    title: "Eppur mi son scordato di te",
    artist: "Mina",
    year: "1985",
  },
  {
    id: "2oVvW4wbCGjtAOvatvYAFu",
    durationMs: 252333,
    title: "Eppure Sentire (un senso di te)",
    artist: "Elisa",
    year: "2006",
  },
  {
    id: "0fXVvo53LoppQI9Hx8FoOo",
    durationMs: 252453,
    title: "Era già tutto previsto",
    artist: "Riccardo Cocciante",
    year: "1975",
  },
  {
    id: "7Co4JFHHRVoAf9lCx37aGx",
    durationMs: 209117,
    title: "Fango in Paradiso",
    artist: "Francesca Michielin",
    year: "2025",
  },
  {
    id: "0d28khcov6AiegSCpG5TuT",
    durationMs: 222640,
    title: "Feel Good Inc.",
    artist: "Gorillaz;De La Soul",
    year: "2005",
  },
  {
    id: "0C9rBeWAsPhmBeaYKZLN5m",
    durationMs: 275480,
    title: "Figli Delle Stelle",
    artist: "Alan Sorrenti",
    year: "1977",
  },
  {
    id: "51Z0G9wCaGl2pcBISoJu9x",
    durationMs: 192256,
    title: "Fiori rosa, fiori di pesco",
    artist: "Lucio Battisti",
    year: "1970",
  },
  {
    id: "5jOAhQaBlo4MsuL6pFjtli",
    durationMs: 297333,
    title: "Firenze - Canzone triste",
    artist: "Ivan Graziani",
    year: "1980",
  },
  {
    id: "3u5N55tHf7hXATSQrjBh2q",
    durationMs: 213333,
    title: "Freed From Desire",
    artist: "Gala;Molella;Phil Jay",
    year: "1996",
  },
  {
    id: "18NBoQ9SyURVcsPW6sP8tv",
    durationMs: 189440,
    title: "Frosinone",
    artist: "Calcutta",
    year: "2015",
  },
  {
    id: "37yIrMPeJYRm7zJ8rr3Uvv",
    durationMs: 238586,
    title: "Funkytown",
    artist: "Lipps Inc",
    year: "1979",
  },
  {
    id: "2oBXn8htpoyjRqrkIGGm0a",
    durationMs: 310266,
    title: "Fuori Dal Tunnel",
    artist: "Caparezza",
    year: "2003",
  },
  {
    id: "5ara7YRzxZ27IwmPWEoNkr",
    durationMs: 366706,
    title: "Futura",
    artist: "Lucio Dalla",
    year: "1980",
  },
  {
    id: "03UrZgTINDqvnUMbbIMhql",
    durationMs: 219493,
    title: "Gangnam Style",
    artist: "PSY",
    year: "2012",
  },
  {
    id: "3ov7Ej1082hP2tegMtVx4L",
    durationMs: 214173,
    title: "Gelato Al Cioccolato",
    artist: "Pupo",
    year: "1979",
  },
  {
    id: "6hwawJtSqgzNfYfLfqTv2p",
    durationMs: 259626,
    title: "Generale",
    artist: "Francesco De Gregori",
    year: "1978",
  },
  {
    id: "5XJMc1j7M2b4l5v6fBYaNO",
    durationMs: 180000,
    title: "giochi di gambe",
    artist: "Giorgio Poi;faccianuvola",
    year: "2025",
  },
  {
    id: "74CjS2xMK4KLnniXzFB9GI",
    durationMs: 274173,
    title: "Gli anni",
    artist: "883",
    year: "1998",
  },
  {
    id: "35tzxthMBglBMjmZ7Fn1hj",
    durationMs: 264674,
    title: "Gloria",
    artist: "Umberto Tozzi",
    year: "1979",
  },
  {
    id: "0PQFPcSK1gnBGlbV4CZCG0",
    durationMs: 495400,
    title: "Good Times",
    artist: "CHIC",
    year: "1979",
  },
  {
    id: "7djxemkRcsWAqrWTye4Vxt",
    durationMs: 240933,
    title: "Grande, grande, grande",
    artist: "Mina",
    year: "1971",
  },
  {
    id: "0pSqOevc0RI5dHLyydQSld",
    durationMs: 229586,
    title: "Guantanamera (Guajira)",
    artist: "Zucchero",
    year: "2012",
  },
  {
    id: "5aowfqA6aFjK1FScZmg4pN",
    durationMs: 251653,
    title: "Hanno ucciso l'Uomo Ragno",
    artist: "883",
    year: "1992",
  },
  {
    id: "3gkUxsWHTvH6jVhr3PCxLY",
    durationMs: 250239,
    title: "Happy Hour",
    artist: "Ligabue",
    year: "2005",
  },
  {
    id: "1JO1xLtVc8mWhIoE3YaCL0",
    durationMs: 176293,
    title: "Happy Together",
    artist: "The Turtles",
    year: "1967",
  },
  {
    id: "7CHlVPgjG1Ti7YLi09tqV8",
    durationMs: 184026,
    title: "Ho un sassolino nella scarpa",
    artist: "Natalino Otto",
    year: "1943",
  },
  {
    id: "4aVuWgvD0X63hcOCnZtNFA",
    durationMs: 235552,
    title: "Hold the Line",
    artist: "TOTO",
    year: "1978",
  },
  {
    id: "6Rb0ptOEjBjPPQUlQtQGbL",
    durationMs: 237640,
    title: "Hotel Room Service",
    artist: "Pitbull",
    year: "2009",
  },
  {
    id: "46cqVRbWixI8Rc6BikLnAe",
    durationMs: 188500,
    title: "HYPERTROIA",
    artist: "HACHIKO",
    year: "2026",
  },
  {
    id: "4h9wh7iOZ0GGn8QVp4RAOB",
    durationMs: 148485,
    title: "I Ain't Worried",
    artist: "OneRepublic",
    year: "2022",
  },
  {
    id: "2Cdvbe2G4hZsnhNMKyGrie",
    durationMs: 175173,
    title: "I Love Rock N Roll",
    artist: "Joan Jett & the Blackhearts",
    year: "1981",
  },
  {
    id: "2tUBqZG2AbRi7Q0BIrVrEj",
    durationMs: 292875,
    title: "I Wanna Dance with Somebody",
    artist: "Whitney Houston",
    year: "1987",
  },
  {
    id: "3gEO96MkIShkDIQuJRry0S",
    durationMs: 415466,
    title: "I Want Your Love",
    artist: "CHIC",
    year: "1978",
  },
  {
    id: "3SnGymj6ijE2iuUfWxLo1q",
    durationMs: 323346,
    title: "I'm Coming Out",
    artist: "Diana Ross",
    year: "1980",
  },
  {
    id: "0N6X297zDahWGWGDO0ulpC",
    durationMs: 166800,
    title: "Il ballo del qua qua",
    artist: "Romina Power",
    year: "1981",
  },
  {
    id: "6oC8FuowgLT4ZSlXECLCNX",
    durationMs: 203573,
    title: "Il ballo di San Vito",
    artist: "Vinicio Capossela",
    year: "1996",
  },
  {
    id: "2DRLmJgblGkqOwxP5OH2PR",
    durationMs: 238240,
    title: "Il Cerchio della Vita",
    artist: "Ivana Spagna",
    year: "1994",
  },
  {
    id: "37C6DyoMu75ViTiwqxV4bY",
    durationMs: 172933,
    title: "Il cielo in una stanza",
    artist: "Gino Paoli",
    year: "1960",
  },
  {
    id: "5ZSzAggKFjyIL6OLA2xUUg",
    durationMs: 178546,
    title: "Il gatto e la volpe",
    artist: "Edoardo Bennato",
    year: "1977",
  },
  {
    id: "2SvXqxiG2ntfkEWvuABT7u",
    durationMs: 308617,
    title: "Il mio canto libero",
    artist: "Lucio Battisti",
    year: "1972",
  },
  {
    id: "0i4mLwfyxnSSgF6hwIkU2L",
    durationMs: 140173,
    title: "Il pescatore",
    artist: "Fabrizio De André",
    year: "1970",
  },
  {
    id: "5Fc7LXJHo8G333kXJRzKC7",
    durationMs: 251115,
    title: "Il ragazzo della via Gluck",
    artist: "Adriano Celentano",
    year: "1966",
  },
  {
    id: "35eRQZmxwjgn7mQrsmtA4f",
    durationMs: 228600,
    title: "Il Regalo Più Grande",
    artist: "Tiziano Ferro",
    year: "2008",
  },
  {
    id: "7C8kVsBSMYqmu190O2lbS5",
    durationMs: 202960,
    title: "Il Solito Sesso",
    artist: "Max Gazzè",
    year: "2008",
  },
  {
    id: "77OdVXaJrgbXpjXscYmJRb",
    durationMs: 269093,
    title: "In alto mare",
    artist: "Loredana Bertè",
    year: "1980",
  },
  {
    id: "09jv6S4KKCafPzreGpWcfp",
    durationMs: 190440,
    title: "In ginocchio da te",
    artist: "Gianni Morandi",
    year: "1964",
  },
  {
    id: "1d07XYsL7hbfLrr8gnDxNr",
    durationMs: 291173,
    title: "In questo mondo di ladri",
    artist: "Antonello Venditti",
    year: "1988",
  },
  {
    id: "60a0Rd6pjrkxjPbaKzXjfq",
    durationMs: 216880,
    title: "In the End",
    artist: "Linkin Park",
    year: "2000",
  },
  {
    id: "19OI21O5twbekJ3xoFQ7RI",
    durationMs: 246466,
    title: "Io come farò",
    artist: "Ornella Vanoni",
    year: "1989",
  },
  {
    id: "3KpKJkiyv02oxxSiIzKKQO",
    durationMs: 174000,
    title: "Io Non Piango",
    artist: "Franco Califano",
    year: "1977",
  },
  {
    id: "1XZp9CsjFdnZuiNzcGYKgP",
    durationMs: 233373,
    title: "Io vagabondo",
    artist: "Nomadi",
    year: "1972",
  },
  {
    id: "6Qyc6fS4DsZjB2mRW9DsQs",
    durationMs: 289533,
    title: "Iris",
    artist: "The Goo Goo Dolls",
    year: "1998",
  },
  {
    id: "2IvetNzSZMH5gwjInoyr18",
    durationMs: 325426,
    title: "It's Raining Men",
    artist: "Weather Girls",
    year: "1982",
  },
  {
    id: "4gphxUgq0JSFv2BCLhNDiE",
    durationMs: 149232,
    title: "Jailhouse Rock",
    artist: "Elvis Presley",
    year: "1957",
  },
  {
    id: "3K0SJUQNbOkUprTFcwwAKN",
    durationMs: 186533,
    title: "Jungle Boogie",
    artist: "Kool & The Gang",
    year: "1973",
  },
  {
    id: "6RyJ57TU2qJCw3GIv9Ag1B",
    durationMs: 207360,
    title: "Kobra",
    artist: "Donatella Rettore",
    year: "1980",
  },
  {
    id: "1YaSQXYPqhwtw35Wf3Z0nI",
    durationMs: 211453,
    title: "L'Amore Non Mi Basta",
    artist: "Emma",
    year: "2013",
  },
  {
    id: "39efIaQFmERjt8U71FrJzs",
    durationMs: 247533,
    title: "L'Emozione Non Ha voce (Io Non So Parlar D'Amore)",
    artist: "Adriano Celentano",
    year: "1999",
  },
  {
    id: "116u2QIEVBnonmFpr8VqBg",
    durationMs: 200520,
    title: "L'Era Del Cinghiale Bianco",
    artist: "Franco Battiato",
    year: "1979",
  },
  {
    id: "1eEMDXRpkipdhKj9nZliol",
    durationMs: 225440,
    title: "L'estate sta finendo",
    artist: "Righeira",
    year: "1985",
  },
  {
    id: "57qOMZrbvnYyPRLodmnQk8",
    durationMs: 240506,
    title: "L'isola che non c'è",
    artist: "Edoardo Bennato",
    year: "1980",
  },
  {
    id: "2S7RApTsKT0CtYojYq2cKz",
    durationMs: 236546,
    title: "L'italiano",
    artist: "Toto Cutugno",
    year: "1983",
  },
  {
    id: "6sLvuv1jCoMzZXNvFCbDzl",
    durationMs: 150760,
    title: "L'uccellino della comare",
    artist: "Sandra e Massimo",
    year: "1998",
  },
  {
    id: "0uMMLry3hzWGn3q3loqMkm",
    durationMs: 174186,
    title: "La Bamba",
    artist: "Los Lobos",
    year: "1987",
  },
  {
    id: "5UmGJS0jd1r52OjnNvVHvU",
    durationMs: 199106,
    title: "La Bomba",
    artist: "Alan Duffy",
    year: "2000",
  },
  {
    id: "5XAGVMePJNaXHcdRN578Xi",
    durationMs: 324826,
    title: "La canzone del sole",
    artist: "Lucio Battisti",
    year: "1971",
  },
  {
    id: "0txZSVRp86nluHUhd1SbA9",
    durationMs: 199373,
    title: "La canzone dell'amore perduto",
    artist: "Fabrizio De André",
    year: "1966",
  },
  {
    id: "6oYcyS6salzWI1ysjEScFh",
    durationMs: 188975,
    title: "LA CODA DEL DIAVOLO (con ELODIE)",
    artist: "Rkomi;Elodie",
    year: "2021",
  },
  {
    id: "1barmMRNFXuBEWNyWvbUwI",
    durationMs: 298880,
    title: "La collina dei ciliegi",
    artist: "Lucio Battisti",
    year: "1973",
  },
  {
    id: "7gUOmOhe5xO20Hu0bXR9SC",
    durationMs: 181000,
    title: "La Coppia Più Bella Del Mondo",
    artist: "Adriano Celentano",
    year: "1967",
  },
  {
    id: "2T2t1DXwzdilKF3BQPHREo",
    durationMs: 279706,
    title: "La donna cannone",
    artist: "Francesco De Gregori",
    year: "1983",
  },
  {
    id: "2LsbizbOeNa4x6qsi2jAMb",
    durationMs: 261200,
    title: "La flaca",
    artist: "Jarabe De Palo",
    year: "1996",
  },
  {
    id: "1lNop22I4dLz5MYuc60fUX",
    durationMs: 181893,
    title: "La guerra di Piero",
    artist: "Fabrizio De André",
    year: "1964",
  },
  {
    id: "6r8k1vznHrzlEKYxL4dZEe",
    durationMs: 242733,
    title: "La Isla Bonita",
    artist: "Madonna",
    year: "1986",
  },
  {
    id: "2w2VPjwO34HBcWGMejcFAA",
    durationMs: 258933,
    title: "La leva calcistica della classe '68",
    artist: "Francesco De Gregori",
    year: "1982",
  },
  {
    id: "6fB3Wy1x9EdhfFwqy8lJcZ",
    durationMs: 232000,
    title: "La mia banda suona il Rock",
    artist: "Ivano Fossati",
    year: "1979",
  },
  {
    id: "6JuqS34gicxFr92kO7D2Hm",
    durationMs: 218012,
    title: "La mia libertà",
    artist: "Franco Califano",
    year: "1981",
  },
  {
    id: "0kM3bPNUPgxaeOf7VzRQer",
    durationMs: 202613,
    title: "La Mia Signorina",
    artist: "Neffa",
    year: "2001",
  },
  {
    id: "56i7VC28M9eCBRMZ5autBG",
    durationMs: 187193,
    title: "La moto Morini",
    artist: "Mal Traa Insema",
    year: "1970",
  },
  {
    id: "7MMJa7cjMadOSR6CFWvB1x",
    durationMs: 222786,
    title: "La musica non c'è",
    artist: "Coez",
    year: "2017",
  },
  {
    id: "49R1F3rIdSzuPk7AcHi6d1",
    durationMs: 189124,
    title: "la noia",
    artist: "Angelina Mango",
    year: "2024",
  },
  {
    id: "2m3BCcthxDo4o4JTJ3CejS",
    durationMs: 248640,
    title: "La paranza",
    artist: "Daniele Silvestri",
    year: "2007",
  },
  {
    id: "2TtT6prILO9coEbbbMGDjv",
    durationMs: 135400,
    title: "La Partita Di Pallone",
    artist: "Rita Pavone",
    year: "1962",
  },
  {
    id: "4NdxkvCNQnb4w56Ytq8y8O",
    durationMs: 245240,
    title: "La regola dell'amico",
    artist: "883",
    year: "1997",
  },
  {
    id: "4tKiqgP4hiFNSCDeoaNctg",
    durationMs: 315533,
    title: "La sera dei miracoli",
    artist: "Lucio Dalla",
    year: "1980",
  },
  {
    id: "7eeAVOoaHu2C4zRwzoECIT",
    durationMs: 281333,
    title: "La terra dei cachi",
    artist: "Elio e le Storie Tese",
    year: "1996",
  },
  {
    id: "0BZoZbffwUSf4cn9gdXX2S",
    durationMs: 194400,
    title: "La tipica ragazza italiana",
    artist: "Dj Matrix",
    year: "2011",
  },
  {
    id: "2UZi7uA5vR0msMzGwFuq5f",
    durationMs: 91040,
    title: "La vendemia",
    artist: "Daisy Lumini",
    year: "1968",
  },
  {
    id: "1mm53EPuBqamMLCr0AoCQS",
    durationMs: 302280,
    title: "La Verità",
    artist: "Brunori Sas",
    year: "2017",
  },
  {
    id: "4kKdvXD0ez7jp1296JmAts",
    durationMs: 155453,
    title: "Let It Snow! Let It Snow! Let It Snow!",
    artist: "Frank Sinatra;B. Swanson Quartet",
    year: "1950",
  },
  {
    id: "4hfIVhq0F0zFUcrbecsYmo",
    durationMs: 217733,
    title: "Let's Get It Started",
    artist: "Black Eyed Peas",
    year: "2003",
  },
  {
    id: "76pyWH7ZLr6q4kJZS3MmEE",
    durationMs: 299373,
    title: "Live Is Life",
    artist: "Opus",
    year: "1984",
  },
  {
    id: "0Ph6L4l8dYUuXFmb71Ajnd",
    durationMs: 243160,
    title: "Livin' la Vida Loca",
    artist: "Ricky Martin",
    year: "1999",
  },
  {
    id: "6JtY7BCKnfIlKoiglSMZhl",
    durationMs: 179586,
    title: "Lo sto sognando",
    artist: "Checco Zalone;",
    year: "2009",
  },
  {
    id: "15JINEqzVMv3SvJTAXAKED",
    durationMs: 263373,
    title: "Love the Way You Lie",
    artist: "Eminem;Rihanna",
    year: "2010",
  },
  {
    id: "2Jpikj1YZnA4XQYVU8yD4z",
    durationMs: 258600,
    title: "Luci a San Siro",
    artist: "Roberto Vecchioni",
    year: "1971",
  },
  {
    id: "0vk46qEN6DEzancOurslfM",
    durationMs: 183626,
    title: "Ma Che Freddo Fa",
    artist: "Nada",
    year: "1969",
  },
  {
    id: "5L8Rn7mlU4I5RuqUBj3MLy",
    durationMs: 187559,
    title: "Ma guardatela",
    artist: "Edoardo Vianello",
    year: "1959",
  },
  {
    id: "1L9m2l2lhXgQ3GwmmCx3OK",
    durationMs: 272746,
    title: "Ma il cielo è sempre più blu",
    artist: "Rino Gaetano",
    year: "1975",
  },
  {
    id: "473Vhyn1aGyuAn4s4juJB1",
    durationMs: 187280,
    title: "Ma le gambe",
    artist: "Trio Lescano",
    year: "1938",
  },
  {
    id: "50f0mt35cIwwu3Krk7nS7b",
    durationMs: 262456,
    title: "Ma quale idea",
    artist: "Pino D'Angiò",
    year: "1980",
  },
  {
    id: "0xRDqhYsCW6F9LM4s7gY5z",
    durationMs: 321000,
    title: "Macho Man",
    artist: "Village People",
    year: "1978",
  },
  {
    id: "0bcrOUFQTXyJCC1lT2xfWI",
    durationMs: 253160,
    title: "Maledetta primavera",
    artist: "Loretta Goggi",
    year: "1981",
  },
  {
    id: "2JT02CH8A8lUwB1GwqvxTQ",
    durationMs: 183000,
    title: "Mambo Italiano",
    artist: "Renato Carosone",
    year: "1955",
  },
  {
    id: "6x4tKaOzfNJpEJHySoiJcs",
    durationMs: 220293,
    title: "Mambo No. 5",
    artist: "Lou Bega",
    year: "1999",
  },
  {
    id: "1AsCxLAvSfilIM9ubCf89B",
    durationMs: 233744,
    title: "Maracaibo",
    artist: "Lu Colombo",
    year: "1981",
  },
  {
    id: "5pv2bpJXi0vspHETP1QjIy",
    durationMs: 277920,
    title: "Mare mare",
    artist: "Luca Carboni",
    year: "1992",
  },
  {
    id: "6b37xrsNCWYIUphFBazqD6",
    durationMs: 239986,
    title: "Me Gustas Tu",
    artist: "Manu Chao",
    year: "2001",
  },
  {
    id: "4wb3UG3WkhrvjkjhlBn7dQ",
    durationMs: 207933,
    title: "Me So' Mbriacato",
    artist: "Mannarino",
    year: "2009",
  },
  {
    id: "3F9ByoUqu31xU0I3G5xfVg",
    durationMs: 284373,
    title: "Meet Me Halfway",
    artist: "Black Eyed Peas",
    year: "2009",
  },
  {
    id: "6wxKdEALyryMXAgyiIXmWB",
    durationMs: 213200,
    title: "Mi manchi",
    artist: "Fausto Leali",
    year: "1988",
  },
  {
    id: "5br1K7SqSJSkL4OohYFbNl",
    durationMs: 221333,
    title: "Mi ritorni in mente",
    artist: "Lucio Battisti",
    year: "1969",
  },
  {
    id: "1fugrphRjf2zBZWbvJwQv2",
    durationMs: 185628,
    title: "Mi sei scoppiato dentro il cuore",
    artist: "Mina",
    year: "1966",
  },
  {
    id: "4fwR5b66ud3xUxPEUSID8q",
    durationMs: 171226,
    title: "Mi sono innamorato di te",
    artist: "Luigi Tenco",
    year: "1962",
  },
  {
    id: "29EPnA4KRr1Eb8j835Vxqh",
    durationMs: 259586,
    title: "Mi vendo",
    artist: "Renato Zero",
    year: "1977",
  },
  {
    id: "34E4gEdUXC7chzXMVkTyks",
    durationMs: 191333,
    title: "Milano e Vincenzo",
    artist: "Alberto Fortis",
    year: "1979",
  },
  {
    id: "3JjZz5GolOMxBlIEKGvtWs",
    durationMs: 179400,
    title: "Mille Lire Al Mese",
    artist: "Gilberto Mazzi",
    year: "1939",
  },
  {
    id: "6qdMhG7pRFi0csRlFGvLE4",
    durationMs: 175923,
    title: "MILLE – feat. Orietta Berti",
    artist: "Fedez, Achille Lauro, Orietta Berti",
    year: "2021",
  },
  {
    id: "2u4pRdwTqvB0xSM3t8K2Bz",
    durationMs: 199381,
    title: "Mio fratello è figlio unico",
    artist: "Rino Gaetano",
    year: "1976",
  },
  {
    id: "5dcyltc1ataieXIeTqhH3t",
    durationMs: 195349,
    title: "Missili",
    artist: "Frah Quintale;Giorgio Poi",
    year: "2018",
  },
  {
    id: "4nFNJmjfgBF7jwv2oBC45b",
    durationMs: 505333,
    title: "Money For Nothing",
    artist: "Dire Straits",
    year: "1985",
  },
  {
    id: "5TpJZQe6V0ivkwheolTSRk",
    durationMs: 192040,
    title: "Montagne verdi",
    artist: "Marcella Bella",
    year: "1972",
  },
  {
    id: "4WpmwEdc4RBos8W8icSSxW",
    durationMs: 218186,
    title: "Moonlight Shadow",
    artist: "Mike Oldfield",
    year: "1983",
  },
  {
    id: "0HmQkmfYXRPweIg1ycw1R8",
    durationMs: 291440,
    title: "Morena mía",
    artist: "Miguel Bosé",
    year: "2001",
  },
  {
    id: "4UzVcXufOhGUwF56HT7b8M",
    durationMs: 262533,
    title: "My Immortal",
    artist: "Evanescence",
    year: "2003",
  },
  {
    id: "3spdoTYpuCpmq19tuD0bOe",
    durationMs: 276800,
    title: "My Way",
    artist: "Frank Sinatra",
    year: "1969",
  },
  {
    id: "7zrkOMlUmpdS6COxQykfVU",
    durationMs: 161383,
    title: "Nessuno Mi Può Giudicare",
    artist: "Caterina Caselli",
    year: "1966",
  },
  {
    id: "4PTG3Z6ehGkBFwjybzWkR8",
    durationMs: 213573,
    title: "Never Gonna Give You Up",
    artist: "Rick Astley",
    year: "1987",
  },
  {
    id: "0qemIQjSxcKyf42VPfZnfa",
    durationMs: 212800,
    title: "Night Fever",
    artist: "Bee Gees",
    year: "1977",
  },
  {
    id: "1IkkOlYbhHxGxyxqC5nVOx",
    durationMs: 253573,
    title: "Non dirgli mai",
    artist: "Gigi D'Alessio",
    year: "2000",
  },
  {
    id: "2YdOZTN2ElEYhEuq6zmwT8",
    durationMs: 199200,
    title: "Non sei tu",
    artist: "Gazzelle",
    year: "2017",
  },
  {
    id: "0EOdowktdF7kczBbqstCfF",
    durationMs: 249866,
    title: "Non so che darei",
    artist: "Alan Sorrenti",
    year: "1980",
  },
  {
    id: "5dWDWnIlasGDHFqTkfsWrm",
    durationMs: 207813,
    title: "Non ti scordar mai di me",
    artist: "Giusy Ferreri",
    year: "2008",
  },
  {
    id: "7EOKcZX9TRkIs0nwWbCCbD",
    durationMs: 187698,
    title: "Non è mica te",
    artist: "Eddie Brock",
    year: "2025",
  },
  {
    id: "7F54orEV7IMKtKG5X9Ig9y",
    durationMs: 270426,
    title: "Nord sud ovest est",
    artist: "883",
    year: "1993",
  },
  {
    id: "3C31FLb0QTPyJ5GjLUUXhz",
    durationMs: 188373,
    title: "Novembre",
    artist: "Giusy Ferreri",
    year: "2008",
  },
  {
    id: "5TFD2bmFKGhoCRbX61nXY5",
    durationMs: 183685,
    title: "NuevaYoL",
    artist: "Bad Bunny",
    year: "2025",
  },
  {
    id: "2nLtzopw4rPReszdYBJU6h",
    durationMs: 187520,
    title: "Numb",
    artist: "Linkin Park",
    year: "2003",
  },
  {
    id: "7JtasZPDVxx1LexFkq68R7",
    durationMs: 312000,
    title: "Nuntereggae più",
    artist: "Rino Gaetano",
    year: "1978",
  },
  {
    id: "4EsU1itX1LEPptKwjhGbVl",
    durationMs: 228986,
    title: "Oggi Sono Io",
    artist: "Alex Britti",
    year: "1999",
  },
  {
    id: "5xsIlITnePRLpwbGDDRDLl",
    durationMs: 145573,
    title: "Ogni Volta",
    artist: "Paul Anka",
    year: "1964",
  },
  {
    id: "0DiWol3AO6WpXZgp0goxAV",
    durationMs: 320357,
    title: "One More Time",
    artist: "Daft Punk",
    year: "2000",
  },
  {
    id: "64BbK9SFKH2jk86U3dGj2P",
    durationMs: 255373,
    title: "Otherside",
    artist: "Red Hot Chili Peppers",
    year: "1999",
  },
  {
    id: "4M8filny20Mwlc2gnvtcgU",
    durationMs: 228906,
    title: "P.E.S.",
    artist: "Club Dogo;Giuliano Palma",
    year: "2012",
  },
  {
    id: "5lmjRquEuSSRCYOBsTJRWq",
    durationMs: 198680,
    title: "Paperella Gay",
    artist: "SpJockey;Crypto",
    year: "2016",
  },
  {
    id: "4OQ1G3dyVx0SPUzBiWCNat",
    durationMs: 178053,
    title: "Paracetamolo",
    artist: "Calcutta",
    year: "2018",
  },
  {
    id: "72jbDTw1piOOj770jWNeaG",
    durationMs: 221506,
    title: "Paris",
    artist: "The Chainsmokers",
    year: "2017",
  },
  {
    id: "0ty8CM0Dibp8AujC2xMWZ3",
    durationMs: 215960,
    title: "Parlami D'Amore Mariù",
    artist: "Vittorio De Sica",
    year: "1932",
  },
  {
    id: "3gQIJcDwrN4DP05oXLQt7M",
    durationMs: 194666,
    title: "Partiti adesso",
    artist: "Giusy Ferreri",
    year: "2017",
  },
  {
    id: "2WW9gkCVI1sqWc08I1KcBg",
    durationMs: 199533,
    title: "Pedro",
    artist: "Raffaella Carrà",
    year: "1980",
  },
  {
    id: "5P2sVkO2mhgeDicQc1btfj",
    durationMs: 254666,
    title: "Pensiero stupendo",
    artist: "Patty Pravo",
    year: "1978",
  },
  {
    id: "6lrlFMu06aGPDH0phlCnct",
    durationMs: 211360,
    title: "Per dimenticare",
    artist: "Zero Assoluto",
    year: "2009",
  },
  {
    id: "5QKRTdqD7dgOIWMYXUmD6J",
    durationMs: 251533,
    title: "Perdere l'amore",
    artist: "Massimo Ranieri",
    year: "1988",
  },
  {
    id: "0HpKuz1HfXxRzNnUqfwzgF",
    durationMs: 238893,
    title: "Piccola stella senza cielo",
    artist: "Ligabue",
    year: "1990",
  },
  {
    id: "3PeRV7ha5XOJwsVm8SxzI7",
    durationMs: 190615,
    title: "Pompo Nelle Casse",
    artist: "Power Francers",
    year: "2010",
  },
  {
    id: "2fTsFCKRFQ5M0igJgabnLA",
    durationMs: 223053,
    title: "Price Tag",
    artist: "Jessie J",
    year: "2011",
  },
  {
    id: "0HQf0bd3oSZei450iKuUFR",
    durationMs: 229200,
    title: "Prisencolinensinainciusol",
    artist: "Adriano Celentano",
    year: "1972",
  },
  {
    id: "2pKsnZaXSTmGQKPAkPuJfv",
    durationMs: 149317,
    title: "Puppe a pera - Live",
    artist: "Cecco e Cipo",
    year: "2017",
  },
  {
    id: "5NVKrGAZjusEqZJ7onT9gO",
    durationMs: 168093,
    title: "Quando, Quando, Quando",
    artist: "Tony Renis",
    year: "1962",
  },
  {
    id: "7zelsfhR5SxQRSTXsjatoW",
    durationMs: 166200,
    title: "Quant'è bello lu primmo ammore",
    artist: "Tony Santagata",
    year: "1964",
  },
  {
    id: "0Oj0nsrBu8YrJdR84VWJV0",
    durationMs: 178306,
    title: "Quarantaquattro gatti",
    artist: "Piccolo Coro dell'Antoniano;Zecchino d'Oro",
    year: "1968",
  },
  {
    id: "0x3reuFIL9WfzDdzoigr8p",
    durationMs: 290000,
    title: "Ragazzo Fortunato",
    artist: "Jovanotti",
    year: "1992",
  },
  {
    id: "7MKcM6TfaGKQVFfhstCbOw",
    durationMs: 227840,
    title: "Redemption Song",
    artist: "Bob Marley & The Wailers",
    year: "1980",
  },
  {
    id: "0NAjpcNOjROBcwFNQlcXY9",
    durationMs: 222293,
    title: "Ricominciamo",
    artist: "Adriano Pappalardo",
    year: "1979",
  },
  {
    id: "515XcapFOMtOOiGU31UqNp",
    durationMs: 220640,
    title: "Rimmel",
    artist: "Francesco De Gregori",
    year: "1975",
  },
  {
    id: "1VpEzp0VfgywKm4nlbouTM",
    durationMs: 291053,
    title: "Roma capoccia",
    artist: "Antonello Venditti",
    year: "1972",
  },
  {
    id: "1nLGeFQuY7PFxrou3ezEvP",
    durationMs: 192989,
    title: "Rossetto e caffè",
    artist: "Sal Da Vinci",
    year: "2024",
  },
  {
    id: "0xYkr8xRLT8vbFA1yrSYO1",
    durationMs: 285760,
    title: "Rotolando Verso Sud",
    artist: "Negrita",
    year: "2005",
  },
  {
    id: "7rbqd5c7Fg1CdLqQRab4YO",
    durationMs: 237493,
    title: "Salirò",
    artist: "Daniele Silvestri",
    year: "2002",
  },
  {
    id: "4hJSzUREpdDo8uhgEflbHr",
    durationMs: 283386,
    title: "Sally",
    artist: "Vasco Rossi",
    year: "1996",
  },
  {
    id: "4JhVT1nbnp9eyIU70mUqot",
    durationMs: 261372,
    title: "Samarcanda",
    artist: "Roberto Vecchioni",
    year: "1977",
  },
  {
    id: "3DAFQyYYpTDEuChTS8eTU7",
    durationMs: 214306,
    title: "Sapore di Sale",
    artist: "Gino Paoli",
    year: "1963",
  },
  {
    id: "6lK2xptPzLPmvpE29U4mDH",
    durationMs: 184546,
    title: "Sarà perché ti amo",
    artist: "Ricchi e poveri",
    year: "1981",
  },
  {
    id: "2PzU4IB8Dr6mxV3lHuaG34",
    durationMs: 222813,
    title: "Satisfaction",
    artist: "Rolling Stones",
    year: "1965",
  },
  {
    id: "1G391cbiT3v3Cywg8T7DM1",
    durationMs: 215906,
    title: "Scar Tissue",
    artist: "Red Hot Chili Peppers",
    year: "1999",
  },
  {
    id: "0wP3e5PzSxafy2TRtlayq9",
    durationMs: 215973,
    title: "Scatman (ski-ba-bop-ba-dop-bop)",
    artist: "Scatman John",
    year: "1994",
  },
  {
    id: "7Djndakc0nj5PcKpF8Z67p",
    durationMs: 192560,
    title: "Se bruciasse la città",
    artist: "Massimo Ranieri",
    year: "1970",
  },
  {
    id: "3Qjr2mNDOn24M4Y50hR9hJ",
    durationMs: 184200,
    title: "Se mi lasci non vale",
    artist: "Julio Iglesias",
    year: "1976",
  },
  {
    id: "2bYLru2w0NKtCDiFPgALFE",
    durationMs: 182480,
    title: "Se telefonando",
    artist: "Mina",
    year: "1966",
  },
  {
    id: "4g6BNLYlAei2bppoe5Z3gK",
    durationMs: 198164,
    title: "Sei ottavi",
    artist: "Rino Gaetano",
    year: "1977",
  },
  {
    id: "42FUNUTTu4dhDhca834rd6",
    durationMs: 238493,
    title: "Self Control",
    artist: "Raf",
    year: "1984",
  },
  {
    id: "6gwLtpIJ9xpgu37Nk0O7hy",
    durationMs: 201666,
    title: "Sentimento Pentimento",
    artist: "Neri per Caso",
    year: "1995",
  },
  {
    id: "3ShEGKdskF0ke7iW2u9gjD",
    durationMs: 267333,
    title: "Senza Una Donna",
    artist: "Zucchero",
    year: "1987",
  },
  {
    id: "3kXoKlD84c6OmIcOLfrfEs",
    durationMs: 216022,
    title: "September",
    artist: "Earth, Wind & Fire",
    year: "1978",
  },
  {
    id: "4Ovy5UkvkweOluGd9hoKsR",
    durationMs: 264986,
    title: "Sere nere",
    artist: "Tiziano Ferro",
    year: "2003",
  },
  {
    id: "3dPQuX8Gs42Y7b454ybpMR",
    durationMs: 232106,
    title: "Seven Nation Army",
    artist: "The White Stripes",
    year: "2003",
  },
  {
    id: "2VxeLyX666F8uXCJ0dZF8B",
    durationMs: 215733,
    title: "Shallow",
    artist: "Lady Gaga, Bradley Cooper",
    year: "2018",
  },
  {
    id: "0CuTlmtd8SLVMzzEWcet3B",
    durationMs: 142226,
    title: "Siamo Una Squadra Fortissimi",
    artist: "Checco Zalone",
    year: "2006",
  },
  {
    id: "4CeeEOM32jQcH3eN9Q2dGj",
    durationMs: 301920,
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    year: "1991",
  },
  {
    id: "2bCQHF9gdG5BNDVuEIEnNk",
    durationMs: 257766,
    title: "Smooth Criminalr",
    artist: "Michael Jackson",
    year: "1987",
  },
  {
    id: "2aibwv5hGXSgw7Yru8IYTO",
    durationMs: 334666,
    title: "Snow",
    artist: "Red Hot Chili Peppers",
    year: "2006",
  },
  {
    id: "2Nf0v3mlQYMMOQZV0aAlNQ",
    durationMs: 248013,
    title: "Soli",
    artist: "Toto Cutugno",
    year: "1979",
  },
  {
    id: "62oaDoBveZxvZb94ziiMXi",
    durationMs: 245755,
    title: "Somebody That I Used to Know",
    artist: "Gotye",
    year: "2011",
  },
  {
    id: "63653pPBcMFICrM0PByMOG",
    durationMs: 302853,
    title: "Sono solo Canzonette",
    artist: "Edoardo Bennato",
    year: "1980",
  },
  {
    id: "4SjRtuCDZvO68N2agNkahv",
    durationMs: 217786,
    title: "Sono solo parole",
    artist: "Noemi",
    year: "2012",
  },
  {
    id: "28VLTrPaxvmNfeouDsUkll",
    durationMs: 237946,
    title: "Sotto Casa",
    artist: "Max Gazzè",
    year: "2013",
  },
  {
    id: "1NuO0tyBz42QOelnFbDHPD",
    durationMs: 257733,
    title: "Sotto questo sole",
    artist: "Francesco Baccini",
    year: "1990",
  },
  {
    id: "1dEZlviHVC2Sbm4TmFnmWK",
    durationMs: 242176,
    title: "Spendi spandi effendi",
    artist: "Rino Gaetano",
    year: "1977",
  },
  {
    id: "5CQ30WqJwcep0pYcV4AMNc",
    durationMs: 482830,
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    year: "1971",
  },
  {
    id: "3SdTKo2uVsxFblQjpScoHy",
    durationMs: 180055,
    title: "Stand By Me",
    artist: "Ben E. King",
    year: "1961",
  },
  {
    id: "0pQskrTITgmCMyr85tb9qq",
    durationMs: 254293,
    title: "Starman",
    artist: "David Bowie",
    year: "1972",
  },
  {
    id: "7uZF6CYmfNQ2lqRYqDhSdc",
    durationMs: 113853,
    title: "Stasera mi butto",
    artist: "Rocky Roberts",
    year: "1967",
  },
  {
    id: "4UDmDIqJIbrW0hMBQMFOsM",
    durationMs: 92866,
    title: "Stayin' Alive",
    artist: "Bee Gees",
    year: "1977",
  },
  {
    id: "0NUyAEi7WInhF0SJGVavUG",
    durationMs: 258799,
    title: "Stella Stai",
    artist: "Umberto Tozzi",
    year: "1980",
  },
  {
    id: "6Ahg1hncxUdK0ICqU03BCu",
    durationMs: 172200,
    title: "Superclassico",
    artist: "Ernia",
    year: "2020",
  },
  {
    id: "1TGbX9T3ijObYeak790FSe",
    durationMs: 221696,
    title: "Supponiamo un amore",
    artist: "Rino Gaetano",
    year: "1974",
  },
  {
    id: "2dbaIpJoAk2hhrrX2ljKJo",
    durationMs: 150533,
    title: "Surfin' U.S.A.",
    artist: "The Beach Boys",
    year: "1963",
  },
  {
    id: "6oWLiyRpo1ibp2vKNxHG0T",
    durationMs: 216933,
    title: "Sweet Dreams",
    artist: "Eurythmics",
    year: "1983",
  },
  {
    id: "7e89621JPkKaeDSTQ3avtg",
    durationMs: 283800,
    title: "Sweet Home Alabama",
    artist: "Lynyrd Skynyrd",
    year: "1974",
  },
  {
    id: "6EhPXpRYkwGwg8lx3XiGTI",
    durationMs: 209333,
    title: "Tacata",
    artist: "Tacabro",
    year: "2012",
  },
  {
    id: "3dYD57lRAUcMHufyqn9GcI",
    durationMs: 241688,
    title: "Take Me To Church",
    artist: "Hozier",
    year: "2013",
  },
  {
    id: "15MJ5NThPjj6xhPcts8MiY",
    durationMs: 255733,
    title: "Take My Breath Away",
    artist: "Berlin",
    year: "1986",
  },
  {
    id: "3ZqL7rtfHLxWk7PQnZv7hH",
    durationMs: 231800,
    title: "Tanto pè cantà",
    artist: "Nino Manfredi",
    year: "1970",
  },
  {
    id: "67wVRCHjobnBE40XNlBVGP",
    durationMs: 191973,
    title: "Tappeto di fragole",
    artist: "Modà",
    year: "2011",
  },
  {
    id: "58uxzfDiTqLqEfNyO3ch21",
    durationMs: 243853,
    title: "Tex-Mex",
    artist: "Mina;Ivano Fossati",
    year: "2019",
  },
  {
    id: "5HOpkTTVcmZHnthgyxrIL8",
    durationMs: 213708,
    title: "The Fox",
    artist: "Ylvis",
    year: "2013",
  },
  {
    id: "3yfqSUWxFvZELEM4PmlwIR",
    durationMs: 284200,
    title: "The Real Slim Shady",
    artist: "Eminem",
    year: "2000",
  },
  {
    id: "3S2R0EVwBSAVMd5UMgKTL0",
    durationMs: 357266,
    title: "Thriller",
    artist: "Michael Jackson",
    year: "1982",
  },
  {
    id: "0gAbf0NL9no1Urk1Wj8Uui",
    durationMs: 245693,
    title: "Ti Amo",
    artist: "Umberto Tozzi",
    year: "1977",
  },
  {
    id: "1aIMyZUrzSkRXJgYO0XO3R",
    durationMs: 250893,
    title: "Ti Fa Stare Bene",
    artist: "Caparezza",
    year: "2017",
  },
  {
    id: "52lYqr81fi0H2yVLupzGwy",
    durationMs: 228240,
    title: "Ti regalerò una rosa",
    artist: "Simone Cristicchi",
    year: "2007",
  },
  {
    id: "2IDNV0ttledZreT0JtzFMp",
    durationMs: 272946,
    title: "Ti scatterò una foto",
    artist: "Tiziano Ferro",
    year: "2006",
  },
  {
    id: "3cHyrEgdyYRjgJKSOiOtcS",
    durationMs: 204134,
    title: "Timber",
    artist: "Pitbull",
    year: "2013",
  },
  {
    id: "1IHWl5LamUGEuP4ozKQSXZ",
    durationMs: 243716,
    title: "Tití Me Preguntó",
    artist: "Bad Bunny",
    year: "2022",
  },
  {
    id: "4hv9MeB0ZuzbFFThnQqLPC",
    durationMs: 184400,
    title: "Trinity",
    artist: "Annibale",
    year: "1970",
  },
  {
    id: "4q2lRiodoQnyFO65watkse",
    durationMs: 365160,
    title: "True",
    artist: "Spandau Ballet",
    year: "1983",
  },
  {
    id: "5ez6STfeeuCyahjmGFmudi",
    durationMs: 205682,
    title: "Tu vuo' fa l'americano",
    artist: "Renato Carosone",
    year: "1956",
  },
  {
    id: "3425P4GkmTIF4d5fVETZvZ",
    durationMs: 161706,
    title: "Tuca Tuca",
    artist: "Raffaella Carrà",
    year: "1971",
  },
  {
    id: "0RbhVoxOZE8BniSgmDbaXV",
    durationMs: 274333,
    title: "Tutto il resto e' noia",
    artist: "Franco Califano",
    year: "1976",
  },
  {
    id: "7eAEs2SiV7DtS8b13PGXWZ",
    durationMs: 139133,
    title: "Un bacio a mezzanotte",
    artist: "Quartetto Cetra",
    year: "1953",
  },
  {
    id: "4ONboWX5n2926t6TcJEGHh",
    durationMs: 197093,
    title: "un estate al mare",
    artist: "Giuni Russo",
    year: "1982",
  },
  {
    id: "7B09xj4jnG1763TWkVxazM",
    durationMs: 190634,
    title: "Un'avventura",
    artist: "Lucio Battisti",
    year: "1969",
  },
  {
    id: "3MxghkgO8EVfMQAnUFH0Iu",
    durationMs: 250306,
    title: "Un'emozione da poco",
    artist: "Anna Oxa",
    year: "1978",
  },
  {
    id: "6oyYKWTbYt5Zb8tIiLZbmH",
    durationMs: 304293,
    title: "Unchain My Heart",
    artist: "Joe Cocker",
    year: "1987",
  },
  {
    id: "3d9DChrdc6BOeFsbrZ3Is0",
    durationMs: 264306,
    title: "Under the Bridge",
    artist: "Red Hot Chili Peppers",
    year: "1991",
  },
  {
    id: "6XpjIhIhIA5AGTyk06FNKU",
    durationMs: 243226,
    title: "Uomini soli",
    artist: "Pooh",
    year: "1990",
  },
  {
    id: "3pbtBomO4Zt5gGiqsYeiBH",
    durationMs: 245600,
    title: "Upside Down",
    artist: "Diana Ross",
    year: "1980",
  },
  {
    id: "2tNiJQG6eaLT9y1pqdj5VV",
    durationMs: 310013,
    title: "Vacanze Romane",
    artist: "Matia Bazar",
    year: "1983",
  },
  {
    id: "0rHIXD2GmjixirvBfTUV2b",
    durationMs: 207866,
    title: "Vecchio frack",
    artist: "Domenico Modugno",
    year: "1955",
  },
  {
    id: "7DUs0muJGnpQ4g8N4xC35S",
    durationMs: 183266,
    title: "Vengo Anch'io No tu No",
    artist: "Enzo Jannacci",
    year: "1967",
  },
  {
    id: "424BQDJzOJqfJCZusTvAZP",
    durationMs: 254680,
    title: "Vengo Dalla Luna",
    artist: "Caparezza",
    year: "2003",
  },
  {
    id: "7IBGw13AbUorsu133u6Q0Z",
    durationMs: 240533,
    title: "Vieni A Ballare In Puglia",
    artist: "Caparezza",
    year: "2008",
  },
  {
    id: "5HWaf9xEiclGk3usOlE2Ex",
    durationMs: 123133,
    title: "Viva la pappa col pomodoro",
    artist: "Rita Pavone",
    year: "1964",
  },
  {
    id: "6WVSjBksHbfBVhvZew41iY",
    durationMs: 211410,
    title: "VOCE",
    artist: "Madame",
    year: "2021",
  },
  {
    id: "2srhl7uP5M5uvtG9sQoLSe",
    durationMs: 206986,
    title: "Vola colomba",
    artist: "Nilla Pizzi",
    year: "1952",
  },
  {
    id: "0vzjqLeM8F95Y7uYPVkESU",
    durationMs: 169981,
    title: "Volevo te",
    artist: "Giusy Ferreri",
    year: "2015",
  },
  {
    id: "5Hk4Mpex0s2ndUpDQ5v2rU",
    durationMs: 248893,
    title: "Walk of Life",
    artist: "Dire Straits",
    year: "1985",
  },
  {
    id: "1Je1IMUlBXcx1Fz0WE7oPT",
    durationMs: 173026,
    title: "Wannabe",
    artist: "Spice Girls",
    year: "1996",
  },
  {
    id: "0xmjwnQ3FNE6HuWCt2nHdZ",
    durationMs: 272533,
    title: "Where Is The Love?",
    artist: "Black Eyed Peas",
    year: "2003",
  },
  {
    id: "6mFkJmJqdDVQ1REhVfGgd1",
    durationMs: 338466,
    title: "Wish you were Here",
    artist: "Pink Floyd",
    year: "1975",
  },
  {
    id: "3h0v8BiwP1qzlCX7TXrsDF",
    durationMs: 241106,
    title: "Xdono",
    artist: "Tiziano Ferro",
    year: "2001",
  },
  {
    id: "54OR1VDpfkBuOY5zZjhZAY",
    durationMs: 286800,
    title: "YMCA",
    artist: "Village People",
    year: "1978",
  },
  {
    id: "4kzOYNpDNmkSGs9w6Z7dVB",
    durationMs: 153728,
    title: "Zingara",
    artist: "Iva Zanicchi",
    year: "1969",
  },
  {
    id: "7q3qX7Ees3FZtRFJXWgPZs",
    durationMs: 254640,
    title: "It's Raining Men",
    artist: "Geri Halliwell",
    year: "2001",
  },
  {
    id: "4RyWA7xB7Yu6ws8yAbGexx",
    durationMs: 147326,
    title: "Show",
    artist: "Neffa",
    year: "2025",
  },
  {
    id: "1auxYwYrFRqZP7t3s7w4um",
    durationMs: 219333,
    title: "Ni**as In Paris",
    artist: "JAY-Z;Kanye West",
    year: "2011",
  },
  {
    id: "4vWkC3Qrlu3kAN2ahtQeAw",
    durationMs: 208933,
    title: "...E allora mambo",
    artist: "Vinicio Capossela",
    year: "1991",
  },
  {
    id: "3kccpXjDqsTV7pRDBjRdyr",
    durationMs: 274266,
    title: "... E la luna bussò",
    artist: "Loredana Bertè",
    year: "1979",
  },
  {
    id: "4zGBAwjlJ0TP02mHH8Wpmo",
    durationMs: 169026,
    title: "I Love Rock N Roll",
    artist: "The Arrows",
    year: "1975",
  },
  {
    id: "2Mc4mdbLGW4ti1Ai6PEFp7",
    durationMs: 257733,
    title: "Le cose in comune",
    artist: "Daniele Silvestri",
    year: "1995",
  },
  {
    id: "1r299qCKBLgUS9XJ9m1kEx",
    durationMs: 202640,
    title: "Moves Like Jagger",
    artist: "Maroon 5;Christina Aguilera",
    year: "2011",
  },
  {
    id: "00SmB7n85SKROGjybsyq5i",
    durationMs: 158426,
    title: "Bongo Bong",
    artist: "Manu Chao",
    year: "1998",
  },
  {
    id: "1GIio7BuzB2DCrDMd0pk1z",
    durationMs: 272480,
    title: "La Vasca",
    artist: "Alex Britti",
    year: "2000",
  },
  {
    id: "4kLLWz7srcuLKA7Et40PQR",
    durationMs: 289133,
    title: "I Gotta Feeling",
    artist: "Black Eyed Peas",
    year: "2009",
  },
  {
    id: "2XbwFs07dfm2MGQuYmRMZT",
    durationMs: 235840,
    title: "Rapper's Delight",
    artist: "The Sugarhill Gang",
    year: "1979",
  },
];
